name = "greendlinger-dehn"
version = "0.1.0"
keywords = ["math", "group-theory", "small-cancellation"]
defaultTargets = ["SmallCancellation"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "065356127b1dc0016f66b7283ce0ce2c4055aa55"

[[lean_lib]]
name = "SmallCancellation"

[[lean_lib]]
name = "Challenge"
roots = ["Challenge"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]
