import SmallCancellation.EdgeFold
import SmallCancellation.Cancellation

namespace GreendlingerDehn

universe u

/-- A combinatorial edge skeleton: every dart has a source and target, and edge
reversal swaps those endpoints. The same structure can be folded repeatedly. -/
structure DartGraph where
  Dart : Type u
  Vertex : Type u
  reverse : Dart → Dart
  source : Dart → Vertex
  target : Dart → Vertex
  reverse_involutive : Function.Involutive reverse
  source_reverse : ∀ d, source (reverse d) = target d
  target_reverse : ∀ d, target (reverse d) = source d

/-- Vertex identifications forced by folding the oppositely traversed darts
`a` and `b`. -/
def VertexFoldGenerator (G : DartGraph) (a b : G.Dart)
    (x y : G.Vertex) : Prop :=
  (x = G.source a ∧ y = G.target b) ∨
    (x = G.target a ∧ y = G.source b)

/-- Vertex equivalence relation generated by a dart fold. -/
def VertexFoldSetoid (G : DartGraph) (a b : G.Dart) : Setoid G.Vertex :=
  Relation.EqvGen.setoid (VertexFoldGenerator G a b)

/-- Vertices after a single edge fold. -/
abbrev FoldedVertex (G : DartGraph) (a b : G.Dart) :=
  Quotient (VertexFoldSetoid G a b)

namespace DartGraph

/-- The source endpoint descends through the edge-fold quotient. -/
def foldedSource (G : DartGraph) (a b : G.Dart) :
    FoldedDart G.reverse a b → FoldedVertex G a b :=
  Quotient.lift (fun d => Quotient.mk (VertexFoldSetoid G a b) (G.source d))
    (by
      intro x y hxy
      apply Quotient.sound
      induction hxy with
      | rel x y h =>
          rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
          · exact Relation.EqvGen.rel _ _
              (Or.inl ⟨rfl, G.source_reverse b⟩)
          · exact Relation.EqvGen.rel _ _
              (Or.inr ⟨G.source_reverse a, rfl⟩)
      | refl x => exact Relation.EqvGen.refl _
      | symm x y _ ih => exact Relation.EqvGen.symm _ _ ih
      | trans x y z _ _ hxy hyz => exact Relation.EqvGen.trans _ _ _ hxy hyz)

/-- The target endpoint descends through the edge-fold quotient. -/
def foldedTarget (G : DartGraph) (a b : G.Dart) :
    FoldedDart G.reverse a b → FoldedVertex G a b :=
  Quotient.lift (fun d => Quotient.mk (VertexFoldSetoid G a b) (G.target d))
    (by
      intro x y hxy
      apply Quotient.sound
      induction hxy with
      | rel x y h =>
          rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
          · exact Relation.EqvGen.rel _ _
              (Or.inr ⟨rfl, G.target_reverse b⟩)
          · exact Relation.EqvGen.rel _ _
              (Or.inl ⟨G.target_reverse a, rfl⟩)
      | refl x => exact Relation.EqvGen.refl _
      | symm x y _ ih => exact Relation.EqvGen.symm _ _ ih
      | trans x y z _ _ hxy hyz => exact Relation.EqvGen.trans _ _ _ hxy hyz)

theorem foldedEndpointEq (G : DartGraph) (a b : G.Dart) :
    (Quotient.mk (VertexFoldSetoid G a b) (G.source a) : FoldedVertex G a b) =
      Quotient.mk (VertexFoldSetoid G a b) (G.target b) := by
  apply Quotient.sound
  exact Relation.EqvGen.rel _ _ (Or.inl ⟨rfl, rfl⟩)

theorem foldedSource_reverse (G : DartGraph) (a b : G.Dart)
    (d : FoldedDart G.reverse a b) :
    G.foldedSource a b (foldedReverse a b G.reverse_involutive d) =
      G.foldedTarget a b d := by
  refine Quotient.inductionOn d ?_
  intro x
  change Quotient.mk (VertexFoldSetoid G a b) (G.source (G.reverse x)) =
    Quotient.mk (VertexFoldSetoid G a b) (G.target x)
  rw [G.source_reverse x]

theorem foldedTarget_reverse (G : DartGraph) (a b : G.Dart)
    (d : FoldedDart G.reverse a b) :
    G.foldedTarget a b (foldedReverse a b G.reverse_involutive d) =
      G.foldedSource a b d := by
  refine Quotient.inductionOn d ?_
  intro x
  change Quotient.mk (VertexFoldSetoid G a b) (G.target (G.reverse x)) =
    Quotient.mk (VertexFoldSetoid G a b) (G.source x)
  rw [G.target_reverse x]

/-- One edge fold quotients both darts and endpoints. The descended reversal
still swaps source and target, so this result can be folded again. -/
def foldedGraph (G : DartGraph) (a b : G.Dart) : DartGraph where
  Dart := FoldedDart G.reverse a b
  Vertex := FoldedVertex G a b
  reverse := foldedReverse a b G.reverse_involutive
  source := G.foldedSource a b
  target := G.foldedTarget a b
  reverse_involutive := foldedReverse_involutive a b G.reverse_involutive
  source_reverse := G.foldedSource_reverse a b
  target_reverse := G.foldedTarget_reverse a b

end DartGraph

/-- An edge skeleton whose darts carry signed generator labels compatible with
edge reversal. -/
structure LabelledDartGraph (α : Type*) extends DartGraph where
  label : toDartGraph.Dart → Letter α
  label_reverse : ∀ d, label (toDartGraph.reverse d) = inverseLetter (label d)

namespace LabelledDartGraph

theorem inverseLetter_inverse {α : Type*} (a : Letter α) :
    inverseLetter (inverseLetter a) = a := by
  cases a with
  | mk x b => cases b <;> rfl

/-- The edge label descends through a fold exactly when the two folded
boundary darts have inverse labels. -/
def foldedLabel {α : Type*} (G : LabelledDartGraph α)
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b)) :
    FoldedDart G.toDartGraph.reverse a b → Letter α :=
  Quotient.lift G.label (by
    intro x y hxy
    induction hxy with
    | rel x y h =>
        rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
        · exact hlabels.trans (G.label_reverse b).symm
        · have hreverse := congrArg inverseLetter hlabels
          rw [inverseLetter_inverse] at hreverse
          exact (G.label_reverse a).trans hreverse
    | refl x => rfl
    | symm x y _ ih => exact ih.symm
    | trans x y z _ _ hxy hyz => exact hxy.trans hyz)

theorem foldedLabel_reverse {α : Type*} (G : LabelledDartGraph α)
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b))
    (d : FoldedDart G.toDartGraph.reverse a b) :
    G.foldedLabel a b hlabels
        (foldedReverse a b G.toDartGraph.reverse_involutive d) =
      inverseLetter (G.foldedLabel a b hlabels d) := by
  refine Quotient.inductionOn d ?_
  intro x
  change G.label (G.toDartGraph.reverse x) = inverseLetter (G.label x)
  exact G.label_reverse x

/-- A labeled dart graph remains labeled after a cancellation fold. -/
def folded (α : Type*) (G : LabelledDartGraph α)
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b)) :
    LabelledDartGraph α where
  toDartGraph := G.toDartGraph.foldedGraph a b
  label := G.foldedLabel a b hlabels
  label_reverse := G.foldedLabel_reverse a b hlabels

end LabelledDartGraph

/-- A directed walk recorded by its dart sequence and endpoint equations. -/
inductive DartWalk (G : DartGraph) : G.Vertex → G.Vertex → Type where
  | nil (v : G.Vertex) : DartWalk G v v
  | cons {u v w : G.Vertex} (d : G.Dart)
      (source_eq : G.source d = u) (target_eq : G.target d = v)
      (tail : DartWalk G v w) : DartWalk G u w

namespace DartWalk

/-- Map a walk into the edge-fold quotient graph. -/
def foldMap {G : DartGraph} {u v : G.Vertex}
    (walk : DartWalk G u v) (a b : G.Dart) :
    DartWalk (DartGraph.foldedGraph G a b)
      (Quotient.mk (VertexFoldSetoid G a b) u)
      (Quotient.mk (VertexFoldSetoid G a b) v) :=
  match walk with
  | .nil x => .nil _
  | .cons d hsource htarget tail =>
      .cons (Quotient.mk (EdgeFoldSetoid G.reverse a b) d)
        (congrArg (Quotient.mk (VertexFoldSetoid G a b)) hsource)
        (congrArg (Quotient.mk (VertexFoldSetoid G a b)) htarget)
        (foldMap tail a b)

/-- Folding two oppositely traversed consecutive boundary darts identifies the
outer endpoints, so deleting that backtrack leaves a walk in the quotient. -/
def fold_cancel_backtrack {G : DartGraph} {v : G.Vertex}
    (a b : G.Dart) (tail : DartWalk G (G.target b) v) :
    DartWalk (DartGraph.foldedGraph G a b)
      (Quotient.mk (VertexFoldSetoid G a b) (G.source a))
      (Quotient.mk (VertexFoldSetoid G a b) v) := by
  exact (DartGraph.foldedEndpointEq G a b).symm ▸ tail.foldMap a b

end DartWalk

end GreendlingerDehn
