import SmallCancellation.EdgeFold
import SmallCancellation.Cancellation

namespace GreendlingerDehn

universe u v

/-- A combinatorial edge skeleton: every dart has a source and target, and edge
reversal swaps those endpoints. The same structure can be folded repeatedly. -/
structure DartGraph where
  Dart : Type u
  Vertex : Type u
  reverse : Dart → Dart
  source : Dart → Vertex
  target : Dart → Vertex
  reverse_involutive : Function.Involutive reverse
  source_reverse : ∀ d, source (reverse d) = target d
  target_reverse : ∀ d, target (reverse d) = source d

/-- Forget dart orientation by quotienting the darts of a graph by its
reversal relation. -/
def UnorientedDartSetoid (G : DartGraph) : Setoid G.Dart :=
  { r := fun d e => d = e ∨ d = G.reverse e
    iseqv := {
      refl := fun d => Or.inl rfl
      symm := by
        intro d e h
        rcases h with h | h
        · exact Or.inl h.symm
        · right
          have hreverse := congrArg G.reverse h
          rw [G.reverse_involutive] at hreverse
          exact hreverse.symm
      trans := by
        intro d e f hde hef
        rcases hde with hde | hde <;> rcases hef with hef | hef
        · exact Or.inl (hde.trans hef)
        · exact Or.inr (hde.trans hef)
        · exact Or.inr (hde.trans (congrArg G.reverse hef))
        · exact Or.inl (hde.trans
            ((congrArg G.reverse hef).trans (G.reverse_involutive f)))}
  }

/-- The unoriented edge class represented by a dart. -/
abbrev UnorientedDartClass (G : DartGraph) :=
  Quotient (UnorientedDartSetoid G)

theorem unorientedDartClass_eq_of_reverse {G : DartGraph} {d e : G.Dart}
    (h : d = G.reverse e) :
    (Quotient.mk (UnorientedDartSetoid G) d : UnorientedDartClass G) =
    Quotient.mk (UnorientedDartSetoid G) e := by
  apply Quotient.sound
  exact Or.inr h

theorem unorientedDartClass_eq_iff {G : DartGraph} (d e : G.Dart) :
    (Quotient.mk (UnorientedDartSetoid G) d : UnorientedDartClass G) =
      Quotient.mk (UnorientedDartSetoid G) e ↔
    d = e ∨ d = G.reverse e := by
  constructor
  · exact Quotient.exact
  · intro h
    exact Quotient.sound h

/-- Vertex identifications forced by folding the oppositely traversed darts
`a` and `b`. -/
def VertexFoldGenerator (G : DartGraph) (a b : G.Dart)
    (x y : G.Vertex) : Prop :=
  (x = G.source a ∧ y = G.target b) ∨
    (x = G.target a ∧ y = G.source b)

/-- Vertex equivalence relation generated by a dart fold. -/
def VertexFoldSetoid (G : DartGraph) (a b : G.Dart) : Setoid G.Vertex :=
  Relation.EqvGen.setoid (VertexFoldGenerator G a b)

/-- Vertices after a single edge fold. -/
abbrev FoldedVertex (G : DartGraph) (a b : G.Dart) :=
  Quotient (VertexFoldSetoid G a b)

namespace DartGraph

/-- The source endpoint descends through the edge-fold quotient. -/
def foldedSource (G : DartGraph) (a b : G.Dart) :
    FoldedDart G.reverse a b → FoldedVertex G a b :=
  Quotient.lift (fun d => Quotient.mk (VertexFoldSetoid G a b) (G.source d))
    (by
      intro x y hxy
      apply Quotient.sound
      induction hxy with
      | rel x y h =>
          rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
          · exact Relation.EqvGen.rel _ _
              (Or.inl ⟨rfl, G.source_reverse b⟩)
          · exact Relation.EqvGen.rel _ _
              (Or.inr ⟨G.source_reverse a, rfl⟩)
      | refl x => exact Relation.EqvGen.refl _
      | symm x y _ ih => exact Relation.EqvGen.symm _ _ ih
      | trans x y z _ _ hxy hyz => exact Relation.EqvGen.trans _ _ _ hxy hyz)

/-- The target endpoint descends through the edge-fold quotient. -/
def foldedTarget (G : DartGraph) (a b : G.Dart) :
    FoldedDart G.reverse a b → FoldedVertex G a b :=
  Quotient.lift (fun d => Quotient.mk (VertexFoldSetoid G a b) (G.target d))
    (by
      intro x y hxy
      apply Quotient.sound
      induction hxy with
      | rel x y h =>
          rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
          · exact Relation.EqvGen.rel _ _
              (Or.inr ⟨rfl, G.target_reverse b⟩)
          · exact Relation.EqvGen.rel _ _
              (Or.inl ⟨G.target_reverse a, rfl⟩)
      | refl x => exact Relation.EqvGen.refl _
      | symm x y _ ih => exact Relation.EqvGen.symm _ _ ih
      | trans x y z _ _ hxy hyz => exact Relation.EqvGen.trans _ _ _ hxy hyz)

theorem foldedEndpointEq (G : DartGraph) (a b : G.Dart) :
    (Quotient.mk (VertexFoldSetoid G a b) (G.source a) : FoldedVertex G a b) =
      Quotient.mk (VertexFoldSetoid G a b) (G.target b) := by
  apply Quotient.sound
  exact Relation.EqvGen.rel _ _ (Or.inl ⟨rfl, rfl⟩)

/-- The other pair of endpoints identified by an edge fold. -/
theorem foldedOtherEndpointEq (G : DartGraph) (a b : G.Dart) :
    (Quotient.mk (VertexFoldSetoid G a b) (G.target a) : FoldedVertex G a b) =
      Quotient.mk (VertexFoldSetoid G a b) (G.source b) := by
  apply Quotient.sound
  exact Relation.EqvGen.rel _ _ (Or.inr ⟨rfl, rfl⟩)

theorem foldedSource_reverse (G : DartGraph) (a b : G.Dart)
    (d : FoldedDart G.reverse a b) :
    G.foldedSource a b (foldedReverse a b G.reverse_involutive d) =
      G.foldedTarget a b d := by
  refine Quotient.inductionOn d ?_
  intro x
  change Quotient.mk (VertexFoldSetoid G a b) (G.source (G.reverse x)) =
    Quotient.mk (VertexFoldSetoid G a b) (G.target x)
  rw [G.source_reverse x]

theorem foldedTarget_reverse (G : DartGraph) (a b : G.Dart)
    (d : FoldedDart G.reverse a b) :
    G.foldedTarget a b (foldedReverse a b G.reverse_involutive d) =
      G.foldedSource a b d := by
  refine Quotient.inductionOn d ?_
  intro x
  change Quotient.mk (VertexFoldSetoid G a b) (G.target (G.reverse x)) =
    Quotient.mk (VertexFoldSetoid G a b) (G.source x)
  rw [G.target_reverse x]

/-- One edge fold quotients both darts and endpoints. The descended reversal
still swaps source and target, so this result can be folded again. -/
def foldedGraph (G : DartGraph) (a b : G.Dart) : DartGraph where
  Dart := FoldedDart G.reverse a b
  Vertex := FoldedVertex G a b
  reverse := foldedReverse a b G.reverse_involutive
  source := G.foldedSource a b
  target := G.foldedTarget a b
  reverse_involutive := foldedReverse_involutive a b G.reverse_involutive
  source_reverse := G.foldedSource_reverse a b
  target_reverse := G.foldedTarget_reverse a b

end DartGraph

/-- An edge skeleton whose darts carry signed generator labels compatible with
edge reversal. -/
structure LabelledDartGraph (α : Type*) extends DartGraph where
  label : toDartGraph.Dart → Letter α
  label_reverse : ∀ d, label (toDartGraph.reverse d) = inverseLetter (label d)

namespace LabelledDartGraph

theorem inverseLetter_inverse {α : Type*} (a : Letter α) :
    inverseLetter (inverseLetter a) = a := by
  cases a with
  | mk x b => cases b <;> rfl

/-- The edge label descends through a fold exactly when the two folded
boundary darts have inverse labels. -/
def foldedLabel {α : Type*} (G : LabelledDartGraph α)
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b)) :
    FoldedDart G.toDartGraph.reverse a b → Letter α :=
  Quotient.lift G.label (by
    intro x y hxy
    induction hxy with
    | rel x y h =>
        rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
        · exact hlabels.trans (G.label_reverse b).symm
        · have hreverse := congrArg inverseLetter hlabels
          rw [inverseLetter_inverse] at hreverse
          exact (G.label_reverse a).trans hreverse
    | refl x => rfl
    | symm x y _ ih => exact ih.symm
    | trans x y z _ _ hxy hyz => exact hxy.trans hyz)

theorem foldedLabel_reverse {α : Type*} (G : LabelledDartGraph α)
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b))
    (d : FoldedDart G.toDartGraph.reverse a b) :
    G.foldedLabel a b hlabels
        (foldedReverse a b G.toDartGraph.reverse_involutive d) =
      inverseLetter (G.foldedLabel a b hlabels d) := by
  refine Quotient.inductionOn d ?_
  intro x
  change G.label (G.toDartGraph.reverse x) = inverseLetter (G.label x)
  exact G.label_reverse x

/-- A labeled dart graph remains labeled after a cancellation fold. -/
def folded (α : Type*) (G : LabelledDartGraph α)
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b)) :
    LabelledDartGraph α where
  toDartGraph := G.toDartGraph.foldedGraph a b
  label := G.foldedLabel a b hlabels
  label_reverse := G.foldedLabel_reverse a b hlabels

end LabelledDartGraph

/-- A directed walk whose successive edge labels are exactly a given word.
The word index makes decomposition and cancellation visible to the kernel. -/
inductive LabelledWalk {α : Type u} (G : LabelledDartGraph.{u, v} α) :
    G.toDartGraph.Vertex → G.toDartGraph.Vertex → Word α →
      Type (max u (v + 1)) where
  | nil (v : G.toDartGraph.Vertex) : LabelledWalk G v v []
  | cons {u v w : G.toDartGraph.Vertex} (d : G.toDartGraph.Dart)
      (source_eq : G.toDartGraph.source d = u)
      (target_eq : G.toDartGraph.target d = v)
      {tailWord : Word α}
      (tail : LabelledWalk G v w tailWord) :
      LabelledWalk G u w (G.label d :: tailWord)

namespace LabelledWalk

/-- The dart occurrences in a labeled walk, in word order. -/
def occurrenceDarts {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {word : Word α} :
    LabelledWalk G u v word → List G.toDartGraph.Dart
  | .nil _ => []
  | .cons d _ _ tail => d :: occurrenceDarts tail

/-- Concatenate two endpoint-compatible walks. -/
noncomputable def append {α : Type*} {G : LabelledDartGraph α}
    {u v w : G.toDartGraph.Vertex} {left right : Word α}
    (first : LabelledWalk G u v left)
    (second : LabelledWalk G v w right) :
    LabelledWalk G u w (left ++ right) :=
  match first with
  | .nil x => by simpa using second
  | .cons d hsource htarget tail => by
      simpa using LabelledWalk.cons d hsource htarget
        (LabelledWalk.append tail second)

/-- Reverse a walk and invert its label word. -/
noncomputable def reverse {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {word : Word α}
    (walk : LabelledWalk G u v word) :
    LabelledWalk G v u (FreeGroup.invRev word) := by
  induction walk with
  | nil vertex => exact .nil vertex
  | @cons u v w dart hsource htarget tailWord tailWalk ih =>
      have hsource' : G.toDartGraph.source (G.toDartGraph.reverse dart) = v := by
        rw [G.toDartGraph.source_reverse, htarget]
      have htarget' : G.toDartGraph.target (G.toDartGraph.reverse dart) = u := by
        rw [G.toDartGraph.target_reverse, hsource]
      have hlast : LabelledWalk G v u [inverseLetter (G.label dart)] := by
        simpa [G.label_reverse] using
          (LabelledWalk.cons (G.toDartGraph.reverse dart) hsource' htarget' (.nil u))
      rw [FreeGroup.invRev_cons]
      exact ih.append hlast

/-- Split a labeled walk at a word concatenation, exposing its middle vertex. -/
def split {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} (left right : Word α)
    (walk : LabelledWalk G u v (left ++ right)) :
    Σ mid, LabelledWalk G u mid left × LabelledWalk G mid v right := by
  induction left generalizing u with
  | nil =>
      exact ⟨u, .nil u, by simpa using walk⟩
  | cons a left ih =>
      cases walk with
      | cons d hsource htarget tail =>
          obtain ⟨mid, leftWalk, rightWalk⟩ := ih tail
          exact ⟨mid, .cons d hsource htarget leftWalk, rightWalk⟩

/-- The dart and endpoint data extracted from a one-letter walk. -/
structure SingleEdgeWalk {α : Type*} (G : LabelledDartGraph α)
    {u v : G.toDartGraph.Vertex} (a : Letter α) where
  dart : G.toDartGraph.Dart
  source_eq : G.toDartGraph.source dart = u
  target_eq : G.toDartGraph.target dart = v
  label_eq : G.label dart = a

/-- A walk labeled by one letter consists of one dart with that label. -/
noncomputable def edgeOf {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {a : Letter α}
    (walk : LabelledWalk G u v [a]) :
    SingleEdgeWalk G (u := u) (v := v) a := by
  cases walk with
  | cons d hsource htarget tail =>
      cases tail with
      | nil x => exact ⟨d, hsource, htarget, rfl⟩

@[simp] theorem occurrenceDarts_append {α : Type*} {G : LabelledDartGraph α}
    {u v w : G.toDartGraph.Vertex} {left right : Word α}
    (first : LabelledWalk G u v left) (second : LabelledWalk G v w right) :
    (first.append second).occurrenceDarts =
      first.occurrenceDarts ++ second.occurrenceDarts := by
  induction first with
  | nil => simp [LabelledWalk.append, occurrenceDarts]
  | cons d hsource htarget tail ih =>
      simp [LabelledWalk.append, occurrenceDarts, ih]

@[simp] theorem occurrenceDarts_cast {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {left right : Word α}
    (h : left = right) (walk : LabelledWalk G u v left) :
    (h ▸ walk).occurrenceDarts = walk.occurrenceDarts := by
  cases h
  rfl

@[simp] theorem occurrenceDarts_length {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {word : Word α}
    (walk : LabelledWalk G u v word) :
    walk.occurrenceDarts.length = word.length := by
  induction walk with
  | nil => rfl
  | cons d hsource htarget tail ih => simp [occurrenceDarts, ih]

theorem occurrenceDarts_split {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} (left right : Word α)
    (walk : LabelledWalk G u v (left ++ right)) :
    walk.occurrenceDarts =
      (LabelledWalk.split left right walk).2.1.occurrenceDarts ++
        (LabelledWalk.split left right walk).2.2.occurrenceDarts := by
  induction left generalizing u with
  | nil => simp [LabelledWalk.split, occurrenceDarts]
  | cons a left ih =>
      cases walk with
      | cons d hsource htarget tail =>
          simpa [LabelledWalk.split, occurrenceDarts] using ih tail

theorem occurrenceDarts_edgeOf {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {a : Letter α}
    (walk : LabelledWalk G u v [a]) :
    walk.occurrenceDarts = [walk.edgeOf.dart] := by
  cases walk with
  | cons d hsource htarget tail => cases tail; rfl

end LabelledWalk

/-- A label-preserving map between signed dart graphs. -/
structure LabelledGraphHom {α : Type*}
    (G H : LabelledDartGraph α) where
  mapVertex : G.toDartGraph.Vertex → H.toDartGraph.Vertex
  mapDart : G.toDartGraph.Dart → H.toDartGraph.Dart
  map_reverse : ∀ d,
    H.toDartGraph.reverse (mapDart d) = mapDart (G.toDartGraph.reverse d)
  map_source : ∀ d,
    H.toDartGraph.source (mapDart d) = mapVertex (G.toDartGraph.source d)
  map_target : ∀ d,
    H.toDartGraph.target (mapDart d) = mapVertex (G.toDartGraph.target d)
  map_label : ∀ d, H.label (mapDart d) = G.label d

namespace LabelledGraphHom

/-- Identity map on a labeled dart graph. -/
def id {α : Type*} (G : LabelledDartGraph α) : LabelledGraphHom G G where
  mapVertex := fun x => x
  mapDart := fun x => x
  map_reverse := by intro d; rfl
  map_source := by intro d; rfl
  map_target := by intro d; rfl
  map_label := by intro d; rfl

/-- The canonical labeled graph map into the quotient made by one fold. -/
def fold {α : Type*} (G : LabelledDartGraph α)
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b)) :
    LabelledGraphHom G (G.folded α a b hlabels) where
  mapVertex := Quotient.mk (VertexFoldSetoid G.toDartGraph a b)
  mapDart := Quotient.mk (EdgeFoldSetoid G.toDartGraph.reverse a b)
  map_reverse := by intro d; rfl
  map_source := by intro d; rfl
  map_target := by intro d; rfl
  map_label := by intro d; rfl

/-- A graph homomorphism that already folds an occurrence pair descends
through the corresponding labeled quotient. This is the universal property
needed to compare a direct fold with a sequence of folds. -/
def descendFold {α : Type*} {G H : LabelledDartGraph α}
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b))
    (f : LabelledGraphHom G H)
    (hfold : f.mapDart b = H.toDartGraph.reverse (f.mapDart a)) :
    LabelledGraphHom (G.folded α a b hlabels) H where
  mapVertex := Quotient.lift f.mapVertex (by
    intro x y hxy
    change Relation.EqvGen (VertexFoldGenerator G.toDartGraph a b) x y at hxy
    induction hxy with
    | rel x y h =>
        rcases h with h | h
        · rcases h with ⟨hxa, hyb⟩
          subst x
          subst y
          calc
            f.mapVertex (G.toDartGraph.source a) =
                H.toDartGraph.source (f.mapDart a) := (f.map_source a).symm
            _ = H.toDartGraph.target (f.mapDart b) := by
              rw [hfold, H.toDartGraph.target_reverse]
            _ = f.mapVertex (G.toDartGraph.target b) := f.map_target b
        · rcases h with ⟨hxa, hyb⟩
          subst x
          subst y
          calc
            f.mapVertex (G.toDartGraph.target a) =
                H.toDartGraph.target (f.mapDart a) := (f.map_target a).symm
            _ = H.toDartGraph.source (f.mapDart b) := by
              rw [hfold, H.toDartGraph.source_reverse]
            _ = f.mapVertex (G.toDartGraph.source b) := f.map_source b
    | refl x => rfl
    | symm x y _ ih => exact ih.symm
    | trans x y z _ _ ih₁ ih₂ => exact ih₁.trans ih₂)
  mapDart := Quotient.lift f.mapDart (by
    intro x y hxy
    change Relation.EqvGen
      (EdgeFoldGenerator G.toDartGraph.reverse a b) x y at hxy
    induction hxy with
    | rel x y h =>
        rcases h with h | h
        · rcases h with ⟨hxa, hyb⟩
          subst x
          subst y
          calc
            f.mapDart a = H.toDartGraph.reverse
                (H.toDartGraph.reverse (f.mapDart a)) :=
              (H.toDartGraph.reverse_involutive (f.mapDart a)).symm
            _ = H.toDartGraph.reverse (f.mapDart b) :=
              congrArg H.toDartGraph.reverse hfold.symm
            _ = f.mapDart (G.toDartGraph.reverse b) :=
              f.map_reverse b
        · rcases h with ⟨hxa, hyb⟩
          subst x
          subst y
          calc
            f.mapDart (G.toDartGraph.reverse a) =
                H.toDartGraph.reverse (f.mapDart a) := (f.map_reverse a).symm
            _ = f.mapDart b := hfold.symm
    | refl x => rfl
    | symm x y _ ih => exact ih.symm
    | trans x y z _ _ ih₁ ih₂ => exact ih₁.trans ih₂)
  map_reverse := by
    intro d
    refine Quotient.inductionOn d ?_
    intro x
    exact f.map_reverse x
  map_source := by
    intro d
    refine Quotient.inductionOn d ?_
    intro x
    exact f.map_source x
  map_target := by
    intro d
    refine Quotient.inductionOn d ?_
    intro x
    exact f.map_target x
  map_label := by
    intro d
    refine Quotient.inductionOn d ?_
    intro x
    exact f.map_label x

/-- The descended map agrees with the original map after the one-fold
quotient map. -/
theorem descendFold_mapDart_fold {α : Type*} {G H : LabelledDartGraph α}
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b))
    (f : LabelledGraphHom G H)
    (hfold : f.mapDart b = H.toDartGraph.reverse (f.mapDart a))
    (d : G.toDartGraph.Dart) :
    (descendFold a b hlabels f hfold).mapDart
        ((fold G a b hlabels).mapDart d) = f.mapDart d := rfl

/-- The dart map for a single fold is a quotient map and is surjective. -/
theorem fold_mapDart_surjective {α : Type*} (G : LabelledDartGraph α)
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b)) :
    Function.Surjective (fold G a b hlabels).mapDart := by
  intro d
  refine Quotient.inductionOn d ?_
  intro original
  exact ⟨original, rfl⟩

/-- Compose two label-preserving graph maps. -/
def comp {α : Type*} {G H K : LabelledDartGraph α}
    (second : LabelledGraphHom H K) (first : LabelledGraphHom G H) :
    LabelledGraphHom G K where
  mapVertex := second.mapVertex ∘ first.mapVertex
  mapDart := second.mapDart ∘ first.mapDart
  map_reverse := by
    intro d
    change K.toDartGraph.reverse (second.mapDart (first.mapDart d)) =
      second.mapDart (first.mapDart (G.toDartGraph.reverse d))
    rw [second.map_reverse, first.map_reverse]
  map_source := by
    intro d
    change K.toDartGraph.source (second.mapDart (first.mapDart d)) =
      second.mapVertex (first.mapVertex (G.toDartGraph.source d))
    rw [second.map_source, first.map_source]
  map_target := by
    intro d
    change K.toDartGraph.target (second.mapDart (first.mapDart d)) =
      second.mapVertex (first.mapVertex (G.toDartGraph.target d))
    rw [second.map_target, first.map_target]
  map_label := by
    intro d
    change K.label (second.mapDart (first.mapDart d)) = G.label d
    rw [second.map_label, first.map_label]

end LabelledGraphHom

namespace LabelledWalk

/-- Apply a label-preserving graph map to every dart in a walk. -/
noncomputable def map {α : Type*} {G H : LabelledDartGraph α}
    (f : LabelledGraphHom G H)
    {u v : G.toDartGraph.Vertex} {word : Word α}
    (walk : LabelledWalk G u v word) :
    LabelledWalk H (f.mapVertex u) (f.mapVertex v) word :=
  match walk with
  | .nil x => .nil _
  | .cons d hsource htarget tail =>
      (f.map_label d) ▸
        (LabelledWalk.cons (f.mapDart d)
          ((f.map_source d).trans (congrArg f.mapVertex hsource))
          ((f.map_target d).trans (congrArg f.mapVertex htarget))
          (LabelledWalk.map f tail))

end LabelledWalk

namespace LabelledWalk

/-- Map a labeled walk through a fold whose two selected darts have inverse
labels. Edge labels and the represented word are preserved by the quotient. -/
noncomputable def foldMap {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {word : Word α}
    (walk : LabelledWalk G u v word)
    (a b : G.toDartGraph.Dart)
    (hlabels : G.label a = inverseLetter (G.label b)) :
    LabelledWalk (G.folded α a b hlabels)
      (Quotient.mk (VertexFoldSetoid G.toDartGraph a b) u)
      (Quotient.mk (VertexFoldSetoid G.toDartGraph a b) v) word :=
  match walk with
  | .nil x => .nil _
  | .cons d hsource htarget tail =>
      .cons (Quotient.mk (EdgeFoldSetoid G.toDartGraph.reverse a b) d)
        (congrArg (Quotient.mk (VertexFoldSetoid G.toDartGraph a b)) hsource)
        (congrArg (Quotient.mk (VertexFoldSetoid G.toDartGraph a b)) htarget)
        (foldMap tail a b hlabels)

/-- Splice the two surviving parts of a boundary walk after folding a
consecutive inverse-labeled pair. -/
noncomputable def spliceAcrossFold {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {preWord sufWord : Word α}
    (first : G.toDartGraph.Dart) (second : G.toDartGraph.Dart)
    (before : LabelledWalk G u (G.toDartGraph.source first) preWord)
    (after : LabelledWalk G (G.toDartGraph.target second) v sufWord)
    (hlabels : G.label first = inverseLetter (G.label second)) :
    LabelledWalk (G.folded α first second hlabels)
      (Quotient.mk (VertexFoldSetoid G.toDartGraph first second) u)
      (Quotient.mk (VertexFoldSetoid G.toDartGraph first second) v)
      (preWord ++ sufWord) := by
  let beforeFold := before.foldMap first second hlabels
  let afterFold := after.foldMap first second hlabels
  exact beforeFold.append
    (DartGraph.foldedEndpointEq G.toDartGraph first second ▸ afterFold)

end LabelledWalk

/-- The result of performing folds on a labeled boundary walk. The graph map
records how every original vertex and dart is represented in the quotient. -/
structure WalkFoldResult {α : Type u} (G : LabelledDartGraph.{u, v} α)
    {u₀ v₀ : G.toDartGraph.Vertex} (word : Word α) :
    Type (max u (v + 1)) where
  graph : LabelledDartGraph.{u, v} α
  hom : LabelledGraphHom G graph
  walk : LabelledWalk graph (hom.mapVertex u₀) (hom.mapVertex v₀) word
  hom_surjective : Function.Surjective hom.mapDart

/-- A pair of occurrences in the original graph that may be glued in opposite
orientations. -/
structure LabelledDartPair {α : Type*} (G : LabelledDartGraph α) where
  first : G.toDartGraph.Dart
  second : G.toDartGraph.Dart
  inverse_labels : G.label first = inverseLetter (G.label second)

namespace LabelledDartPair

/-- Move an inverse-labeled occurrence pair through a label-preserving graph
map. -/
def map {α : Type*} {G H : LabelledDartGraph α}
    (f : LabelledGraphHom G H) (pair : LabelledDartPair G) :
    LabelledDartPair H where
  first := f.mapDart pair.first
  second := f.mapDart pair.second
  inverse_labels := by
    rw [f.map_label, f.map_label]
    exact pair.inverse_labels

end LabelledDartPair

/-- Dart identifications generated by a finite list of labeled occurrence
pairs. The pair's two chosen orientations and their reverses are identified
exactly as in a sequence of edge folds. -/
def LabelledDartPairFoldGenerator {α : Type*} {G : LabelledDartGraph α}
    (pairs : List (LabelledDartPair G))
    (d e : G.toDartGraph.Dart) : Prop :=
  ∃ pair ∈ pairs,
    EdgeFoldGenerator G.toDartGraph.reverse pair.first pair.second d e

/-- The dart equivalence relation prescribed by all occurrence pairs. -/
def LabelledDartPairFoldSetoid {α : Type*} {G : LabelledDartGraph α}
    (pairs : List (LabelledDartPair G)) : Setoid G.toDartGraph.Dart :=
  Relation.EqvGen.setoid (LabelledDartPairFoldGenerator pairs)

/-- Reordering a finite list of requested folds leaves the generated dart
identification relation unchanged. -/
theorem LabelledDartPairFoldSetoid_eq_of_perm {α : Type*}
    {G : LabelledDartGraph α}
    {pairs pairs' : List (LabelledDartPair G)}
    (h : pairs.Perm pairs') :
    LabelledDartPairFoldSetoid pairs =
      LabelledDartPairFoldSetoid pairs' := by
  have hgenerator : LabelledDartPairFoldGenerator pairs =
      LabelledDartPairFoldGenerator pairs' := by
    funext d e
    apply propext
    simp only [LabelledDartPairFoldGenerator]
    constructor
    · rintro ⟨pair, hpair, hfold⟩
      exact ⟨pair, h.mem_iff.mp hpair, hfold⟩
    · rintro ⟨pair, hpair, hfold⟩
      exact ⟨pair, h.mem_iff.mpr hpair, hfold⟩
  apply Setoid.ext
  intro d e
  change Relation.EqvGen (LabelledDartPairFoldGenerator pairs) d e ↔
    Relation.EqvGen (LabelledDartPairFoldGenerator pairs') d e
  rw [hgenerator]

private theorem eqvGen_pullback_of_surjective {D E : Type*} (q : D → E)
    (R : E → E → Prop) (K Q : D → D → Prop)
    (hq : Function.Surjective q)
    (hkernel : ∀ a b, q a = q b → K a b)
    (hgenerator : ∀ {x y}, R x y → ∀ a b, q a = x → q b = y →
      Relation.EqvGen (fun d e => K d e ∨ Q d e) a b)
    {x y : E} (h : Relation.EqvGen R x y) {a b : D}
    (hqa : q a = x) (hqb : q b = y) :
    Relation.EqvGen (fun d e => K d e ∨ Q d e) a b := by
  induction h generalizing a b with
  | rel x y hxy =>
      exact hgenerator hxy a b hqa hqb
  | refl x =>
      exact Relation.EqvGen.rel _ _
        (Or.inl (hkernel a b (hqa.trans hqb.symm)))
  | symm x y _ ih =>
      exact Relation.EqvGen.symm _ _
        (ih (a := b) (b := a) hqb hqa)
  | trans x y z _ _ ihxy ihyz =>
      obtain ⟨m, hm⟩ := hq y
      exact Relation.EqvGen.trans _ _ _
        (ihxy (a := a) (b := m) hqa hm)
        (ihyz (a := m) (b := b) hm hqb)

private theorem eqvGen_mono {D : Type*} {R S : D → D → Prop}
    (hsub : ∀ a b, R a b → S a b) {a b : D}
    (h : Relation.EqvGen R a b) : Relation.EqvGen S a b := by
  induction h with
  | rel a b hab => exact Relation.EqvGen.rel _ _ (hsub a b hab)
  | refl a => exact Relation.EqvGen.refl _
  | symm a b _ ih => exact Relation.EqvGen.symm _ _ ih
  | trans a b c _ _ ih₁ ih₂ => exact Relation.EqvGen.trans _ _ _ ih₁ ih₂

private theorem eqvGen_mapClosure {D : Type*} {R S : D → D → Prop}
    (hsub : ∀ a b, R a b → Relation.EqvGen S a b) {a b : D}
    (h : Relation.EqvGen R a b) : Relation.EqvGen S a b := by
  induction h with
  | rel a b hab => exact hsub a b hab
  | refl a => exact Relation.EqvGen.refl _
  | symm a b _ ih => exact Relation.EqvGen.symm _ _ ih
  | trans a b c _ _ ih₁ ih₂ => exact Relation.EqvGen.trans _ _ _ ih₁ ih₂

namespace LabelledGraphHom

/-- If a graph map sends the second occurrence of a pair to the reverse of
the first, it identifies the second source with the first target. -/
theorem mapVertex_source_second_eq_target_first {α : Type*}
    {G H : LabelledDartGraph α} (f : LabelledGraphHom G H)
    (pair : LabelledDartPair G)
    (hpair : f.mapDart pair.second =
      H.toDartGraph.reverse (f.mapDart pair.first)) :
    f.mapVertex (G.toDartGraph.source pair.second) =
      f.mapVertex (G.toDartGraph.target pair.first) := by
  calc
    f.mapVertex (G.toDartGraph.source pair.second) =
        H.toDartGraph.source (f.mapDart pair.second) :=
      (f.map_source pair.second).symm
    _ = H.toDartGraph.source
          (H.toDartGraph.reverse (f.mapDart pair.first)) :=
      congrArg H.toDartGraph.source hpair
    _ = H.toDartGraph.target (f.mapDart pair.first) :=
      H.toDartGraph.source_reverse _
    _ = f.mapVertex (G.toDartGraph.target pair.first) :=
      f.map_target pair.first

end LabelledGraphHom

/-- A successive fold of a list of inverse-labeled dart pairs, together with
the fact that every requested pair becomes opposite orientations of one
quotient edge. -/
structure LabelledDartPairFoldResult {α : Type u}
    (G : LabelledDartGraph.{u, v} α) (pairs : List (LabelledDartPair G)) where
  graph : LabelledDartGraph.{u, v} α
  hom : LabelledGraphHom G graph
  pairs_folded : ∀ pair ∈ pairs,
    hom.mapDart pair.second = graph.toDartGraph.reverse (hom.mapDart pair.first)
  hom_surjective : Function.Surjective hom.mapDart

namespace LabelledDartPairFoldResult

/-- The first fold in a pair list identifies its second dart with the reverse
of its first dart. -/
theorem oneFold_pair_reverse {α : Type u}
    {G : LabelledDartGraph.{u, v} α}
    (pair : LabelledDartPair G) :
    (LabelledGraphHom.fold G pair.first pair.second pair.inverse_labels).mapDart
        pair.second =
      (G.folded α pair.first pair.second pair.inverse_labels).toDartGraph.reverse
        ((LabelledGraphHom.fold G pair.first pair.second pair.inverse_labels).mapDart
          pair.first) := by
  change Quotient.mk (EdgeFoldSetoid G.toDartGraph.reverse pair.first pair.second)
      pair.second =
    foldedReverse pair.first pair.second G.toDartGraph.reverse_involutive
      (Quotient.mk (EdgeFoldSetoid G.toDartGraph.reverse pair.first pair.second)
        pair.first)
  rw [foldedReverse_mk]
  exact (fold_twin_darts_eq pair.first pair.second
    G.toDartGraph.reverse_involutive).symm

/-- Fold all requested pairs in order, transporting each later pair through
the quotients already constructed. -/
noncomputable def foldAll {α : Type u} (G : LabelledDartGraph.{u, v} α) :
    (pairs : List (LabelledDartPair G)) → LabelledDartPairFoldResult G pairs
  | [] => ⟨G, LabelledGraphHom.id G, by simp, by
      intro d
      exact ⟨d, rfl⟩⟩
  | pair :: rest => by
      let firstGraph := G.folded α pair.first pair.second pair.inverse_labels
      let firstHom := LabelledGraphHom.fold G pair.first pair.second pair.inverse_labels
      let transported := rest.map (LabelledDartPair.map firstHom)
      let later := foldAll firstGraph transported
      refine ⟨later.graph, LabelledGraphHom.comp later.hom firstHom, ?_, ?_⟩
      · intro current hmem
        simp only [List.mem_cons] at hmem
        rcases hmem with hhead | htail
        · subst current
          change later.hom.mapDart (firstHom.mapDart pair.second) =
            later.graph.toDartGraph.reverse
              (later.hom.mapDart (firstHom.mapDart pair.first))
          calc
            later.hom.mapDart (firstHom.mapDart pair.second) =
                later.hom.mapDart
                  (firstGraph.toDartGraph.reverse (firstHom.mapDart pair.first)) :=
              congrArg later.hom.mapDart (oneFold_pair_reverse pair)
            _ = later.graph.toDartGraph.reverse
                  (later.hom.mapDart (firstHom.mapDart pair.first)) :=
              (later.hom.map_reverse _).symm
        · have htransported : LabelledDartPair.map firstHom current ∈ transported :=
            List.mem_map.mpr ⟨current, htail, rfl⟩
          have hfolded := later.pairs_folded (LabelledDartPair.map firstHom current)
            htransported
          simpa [LabelledGraphHom.comp, LabelledDartPair.map] using hfolded
      · intro d
        obtain ⟨middle, hmiddle⟩ := later.hom_surjective d
        obtain ⟨original, horiginal⟩ :=
          LabelledGraphHom.fold_mapDart_surjective G pair.first pair.second
            pair.inverse_labels middle
        exact ⟨original, by
          calc
            _ = later.hom.mapDart middle := congrArg later.hom.mapDart horiginal
            _ = d := hmiddle⟩
termination_by pairs => pairs.length
decreasing_by simp

/-- Any pair identification in the source list is respected by the final
successive-fold map. -/
theorem foldAll_mapDart_eq_of_pairFoldSetoid {α : Type u}
    {G : LabelledDartGraph.{u, v} α}
    {pairs : List (LabelledDartPair G)} {d e : G.toDartGraph.Dart}
    (h : (LabelledDartPairFoldSetoid pairs).r d e) :
    (foldAll G pairs).hom.mapDart d = (foldAll G pairs).hom.mapDart e := by
  change Relation.EqvGen (LabelledDartPairFoldGenerator pairs) d e at h
  induction h with
  | rel x y hxy =>
      rcases hxy with ⟨pair, hpair, hgen⟩
      have hfolded := (foldAll G pairs).pairs_folded pair hpair
      rcases hgen with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
      · calc
          _ = (foldAll G pairs).graph.toDartGraph.reverse
                ((foldAll G pairs).hom.mapDart pair.second) := by
                  have hreverse := congrArg
                    (foldAll G pairs).graph.toDartGraph.reverse hfolded
                  rw [(foldAll G pairs).graph.toDartGraph.reverse_involutive] at hreverse
                  exact hreverse.symm
          _ = _ := (foldAll G pairs).hom.map_reverse pair.second
      · calc
          _ = (foldAll G pairs).graph.toDartGraph.reverse
                ((foldAll G pairs).hom.mapDart pair.first) :=
                  (foldAll G pairs).hom.map_reverse pair.first |>.symm
          _ = _ := hfolded.symm
  | refl x => rfl
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ hxy hyz => exact hxy.trans hyz

/-- The final successive-fold map identifies exactly the darts connected by
the occurrence-pair fold generators. -/
theorem foldAll_mapDart_eq_iff_pairFoldSetoid {α : Type u}
    {G : LabelledDartGraph.{u, v} α} :
    (pairs : List (LabelledDartPair G)) →
    (d e : G.toDartGraph.Dart) →
    (foldAll G pairs).hom.mapDart d = (foldAll G pairs).hom.mapDart e ↔
      (LabelledDartPairFoldSetoid pairs).r d e
  | [] => by
      intro d e
      constructor
      · intro h
        have hde : d = e := by
          rw [foldAll.eq_1] at h
          simpa [LabelledGraphHom.id] using h
        subst e
        exact Relation.EqvGen.refl _
      · intro h
        change Relation.EqvGen (LabelledDartPairFoldGenerator []) d e at h
        induction h with
        | rel _ _ hgen => rcases hgen with ⟨p, hp, _⟩; cases hp
        | refl _ => rfl
        | symm _ _ _ ih => exact ih.symm
        | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | pair :: rest => by
      intro d e
      let firstGraph := G.folded α pair.first pair.second pair.inverse_labels
      let firstHom := LabelledGraphHom.fold G pair.first pair.second pair.inverse_labels
      let transported := rest.map (LabelledDartPair.map firstHom)
      let later := foldAll firstGraph transported
      constructor
      · intro h
        have hLater : later.hom.mapDart (firstHom.mapDart d) =
            later.hom.mapDart (firstHom.mapDart e) := by
          rw [foldAll.eq_2] at h
          change (LabelledGraphHom.comp later.hom firstHom).mapDart d =
            (LabelledGraphHom.comp later.hom firstHom).mapDart e at h
          exact h
        have hGenerated : (LabelledDartPairFoldSetoid transported).r
            (firstHom.mapDart d) (firstHom.mapDart e) :=
          (foldAll_mapDart_eq_iff_pairFoldSetoid (G := firstGraph) transported
            (firstHom.mapDart d) (firstHom.mapDart e)).1 hLater
        let K : G.toDartGraph.Dart → G.toDartGraph.Dart → Prop :=
          (EdgeFoldSetoid G.toDartGraph.reverse pair.first pair.second).r
        let Q : G.toDartGraph.Dart → G.toDartGraph.Dart → Prop :=
          LabelledDartPairFoldGenerator rest
        have hGenerator : ∀ {x y}, LabelledDartPairFoldGenerator transported x y →
            ∀ a b, firstHom.mapDart a = x → firstHom.mapDart b = y →
              Relation.EqvGen (fun a b => K a b ∨ Q a b) a b := by
          intro x y hxy a b hqa hqb
          rcases hxy with ⟨transportedPair, htransported, hfold⟩
          rcases List.mem_map.mp htransported with
            ⟨originalPair, horiginal, hmap⟩
          subst transportedPair
          rcases hfold with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
          · have hleft : K a originalPair.first := by
              change (EdgeFoldSetoid G.toDartGraph.reverse pair.first pair.second).r
                a originalPair.first
              exact Quotient.exact hqa
            have hmiddle : Q originalPair.first
                (G.toDartGraph.reverse originalPair.second) :=
              ⟨originalPair, horiginal, Or.inl ⟨rfl, rfl⟩⟩
            have hright : K (G.toDartGraph.reverse originalPair.second) b := by
              change (EdgeFoldSetoid G.toDartGraph.reverse pair.first pair.second).r
                (G.toDartGraph.reverse originalPair.second) b
              apply Quotient.exact
              calc
                firstHom.mapDart (G.toDartGraph.reverse originalPair.second) =
                    firstGraph.toDartGraph.reverse
                      (firstHom.mapDart originalPair.second) :=
                  (firstHom.map_reverse originalPair.second).symm
                _ = firstHom.mapDart b := hqb.symm
            exact Relation.EqvGen.trans _ _ _
              (Relation.EqvGen.rel _ _ (Or.inl hleft))
              (Relation.EqvGen.trans _ _ _
                (Relation.EqvGen.rel _ _ (Or.inr hmiddle))
                (Relation.EqvGen.rel _ _ (Or.inl hright)))
          · have hleft : K a (G.toDartGraph.reverse originalPair.first) := by
              change (EdgeFoldSetoid G.toDartGraph.reverse pair.first pair.second).r
                a (G.toDartGraph.reverse originalPair.first)
              apply Quotient.exact
              calc
                firstHom.mapDart a =
                    firstGraph.toDartGraph.reverse
                      (firstHom.mapDart originalPair.first) := hqa
                _ = firstHom.mapDart (G.toDartGraph.reverse originalPair.first) :=
                  firstHom.map_reverse originalPair.first
            have hmiddle : Q (G.toDartGraph.reverse originalPair.first)
                originalPair.second :=
              ⟨originalPair, horiginal, Or.inr ⟨rfl, rfl⟩⟩
            have hright : K originalPair.second b := by
              change (EdgeFoldSetoid G.toDartGraph.reverse pair.first pair.second).r
                originalPair.second b
              apply Quotient.exact
              exact hqb.symm
            exact Relation.EqvGen.trans _ _ _
              (Relation.EqvGen.rel _ _ (Or.inl hleft))
              (Relation.EqvGen.trans _ _ _
              (Relation.EqvGen.rel _ _ (Or.inr hmiddle))
                (Relation.EqvGen.rel _ _ (Or.inl hright)))
        have hPulled := eqvGen_pullback_of_surjective
          firstHom.mapDart (LabelledDartPairFoldGenerator transported) K Q
          (LabelledGraphHom.fold_mapDart_surjective G pair.first pair.second
            pair.inverse_labels)
          (by
            intro a b hab
            change (EdgeFoldSetoid G.toDartGraph.reverse pair.first pair.second).r
              a b
            exact Quotient.exact hab)
          hGenerator hGenerated rfl rfl
        have hBase : ∀ {a b}, K a b →
            Relation.EqvGen (LabelledDartPairFoldGenerator (pair :: rest)) a b := by
          intro a b hab
          change Relation.EqvGen
            (EdgeFoldGenerator G.toDartGraph.reverse pair.first pair.second) a b at hab
          exact eqvGen_mono
            (fun x y hxy =>
              (show LabelledDartPairFoldGenerator (pair :: rest) x y from
                ⟨pair, List.mem_cons_self, hxy⟩)) hab
        have hIncludes : ∀ {a b}, K a b ∨ Q a b →
            Relation.EqvGen (LabelledDartPairFoldGenerator (pair :: rest)) a b := by
          intro a b hab
          rcases hab with hbase | hrest
          · exact hBase hbase
          · rcases hrest with ⟨p, hp, hfold⟩
            exact Relation.EqvGen.rel _ _
              ⟨p, List.mem_cons_of_mem pair hp, hfold⟩
        change Relation.EqvGen (LabelledDartPairFoldGenerator (pair :: rest)) d e
        exact eqvGen_mapClosure (fun a b hab => hIncludes hab) hPulled
      · intro h
        exact foldAll_mapDart_eq_of_pairFoldSetoid h
termination_by pairs => pairs.length
decreasing_by simp

/-- The direct pair-fold quotient identifies the same original darts when its
requested pairs are listed in any permuted order. -/
theorem foldAll_mapDart_eq_iff_of_perm {α : Type u}
    {G : LabelledDartGraph.{u, v} α}
    {pairs pairs' : List (LabelledDartPair G)}
    (h : pairs.Perm pairs') (d e : G.toDartGraph.Dart) :
    ((foldAll G pairs).hom.mapDart d = (foldAll G pairs).hom.mapDart e) ↔
      ((foldAll G pairs').hom.mapDart d = (foldAll G pairs').hom.mapDart e) := by
  rw [foldAll_mapDart_eq_iff_pairFoldSetoid,
    foldAll_mapDart_eq_iff_pairFoldSetoid,
    LabelledDartPairFoldSetoid_eq_of_perm h]

/-- Any graph map that already folds every requested pair factors through the
successive quotient obtained by folding the whole list. -/
def descendAll {α : Type u} {G H : LabelledDartGraph.{u, v} α}
    (f : LabelledGraphHom G H) :
    (pairs : List (LabelledDartPair G)) →
      (∀ pair ∈ pairs,
      f.mapDart pair.second = H.toDartGraph.reverse (f.mapDart pair.first)) →
    LabelledGraphHom (foldAll G pairs).graph H
  | [], _ => by
      rw [foldAll.eq_1]
      exact f
  | pair :: rest, hfolded => by
      let firstGraph := G.folded α pair.first pair.second pair.inverse_labels
      let firstHom := LabelledGraphHom.fold G pair.first pair.second pair.inverse_labels
      let transported := rest.map (LabelledDartPair.map firstHom)
      let ffirst := LabelledGraphHom.descendFold pair.first pair.second
        pair.inverse_labels f (hfolded pair List.mem_cons_self)
      have htransported : ∀ p ∈ transported,
          ffirst.mapDart p.second = H.toDartGraph.reverse (ffirst.mapDart p.first) := by
        intro p hp
        rcases List.mem_map.mp hp with ⟨original, horiginal, rfl⟩
        change f.mapDart original.second =
          H.toDartGraph.reverse (f.mapDart original.first)
        exact hfolded original (List.mem_cons_of_mem pair horiginal)
      rw [foldAll.eq_2]
      exact descendAll ffirst transported htransported
termination_by pairs => pairs.length
decreasing_by simp

end LabelledDartPairFoldResult

namespace WalkFoldResult

/-- Fold the current images of an original occurrence pair. Earlier folds are
transported through `state.hom`, so repeated use of a source dart remains
well-defined. -/
noncomputable def foldPair {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {word : Word α}
    (state : WalkFoldResult G (u₀ := u) (v₀ := v) word)
    (pair : LabelledDartPair G) :
    WalkFoldResult G (u₀ := u) (v₀ := v) word := by
  let first := state.hom.mapDart pair.first
  let second := state.hom.mapDart pair.second
  have hlabels : state.graph.label first = inverseLetter (state.graph.label second) := by
    rw [state.hom.map_label, state.hom.map_label]
    exact pair.inverse_labels
  let quotientMap := LabelledGraphHom.fold state.graph first second hlabels
  exact ⟨state.graph.folded α first second hlabels,
    LabelledGraphHom.comp quotientMap state.hom,
    state.walk.map quotientMap, by
      intro d
      obtain ⟨middle, hmiddle⟩ :=
        LabelledGraphHom.fold_mapDart_surjective state.graph first second hlabels d
      obtain ⟨original, horiginal⟩ := state.hom_surjective middle
      exact ⟨original, by
        calc
          _ = quotientMap.mapDart middle := congrArg quotientMap.mapDart horiginal
          _ = d := hmiddle⟩⟩

/-- Fold a finite list of original occurrence pairs successively. Every pair is
mapped through all preceding quotients before it is folded. -/
noncomputable def foldPairsFrom {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {word : Word α}
    (state : WalkFoldResult G (u₀ := u) (v₀ := v) word) :
    (pairs : List (LabelledDartPair G)) →
      WalkFoldResult G (u₀ := u) (v₀ := v) word
  | [] => state
  | pair :: rest => foldPairsFrom (state.foldPair pair) rest

/-- Start a finite sequence of occurrence folds from the original graph and
its boundary walk. -/
noncomputable def foldPairs {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {word : Word α}
    (pairs : List (LabelledDartPair G))
    (walk : LabelledWalk G u v word) :
    WalkFoldResult G (u₀ := u) (v₀ := v) word := by
  let folded := LabelledDartPairFoldResult.foldAll G pairs
  exact ⟨folded.graph, folded.hom, walk.map folded.hom, folded.hom_surjective⟩

/-- Every supplied occurrence pair is opposite-oriented in the final graph
after the complete successive fold chain. -/
theorem foldPairs_pair_reverse {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {word : Word α}
    (pairs : List (LabelledDartPair G))
    (walk : LabelledWalk G u v word) (pair : LabelledDartPair G)
    (hpair : pair ∈ pairs) :
    (foldPairs pairs walk).hom.mapDart pair.second =
      (foldPairs pairs walk).graph.toDartGraph.reverse
        ((foldPairs pairs walk).hom.mapDart pair.first) := by
  exact (LabelledDartPairFoldResult.foldAll G pairs).pairs_folded pair hpair

/-- Every requested fold identifies the unoriented edge classes of its two
source occurrences. -/
theorem foldPairs_pair_unorientedClass_eq {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {word : Word α}
    (pairs : List (LabelledDartPair G))
    (walk : LabelledWalk G u v word) (pair : LabelledDartPair G)
    (hpair : pair ∈ pairs) :
    (Quotient.mk
      (UnorientedDartSetoid (foldPairs pairs walk).graph.toDartGraph)
      ((foldPairs pairs walk).hom.mapDart pair.second) :
      UnorientedDartClass (foldPairs pairs walk).graph.toDartGraph) =
      Quotient.mk
        (UnorientedDartSetoid (foldPairs pairs walk).graph.toDartGraph)
        ((foldPairs pairs walk).hom.mapDart pair.first) := by
  apply unorientedDartClass_eq_of_reverse
  exact foldPairs_pair_reverse pairs walk pair hpair

end WalkFoldResult

namespace FreeCancellationStep

/-- The prefix length locating the adjacent inverse letters removed by a
single free-cancellation step. -/
def prefixLength {α : Type*} {raw reduced : Word α}
    (step : FreeCancellationStep raw reduced) : Nat := by
  cases step with
  | cancel pre post a => exact pre.length

/-- A cancellation step removes a pair starting at a valid source position. -/
theorem prefixLength_add_two_le {α : Type*} {raw reduced : Word α}
    (step : FreeCancellationStep raw reduced) :
    step.prefixLength + 2 ≤ raw.length := by
  cases step with
  | cancel pre post a =>
      simp [prefixLength, List.length_append]

/-- The selected position is stable under the word-index cast helper. -/
@[simp] theorem prefixLength_castWords {α : Type*}
    {raw raw' reduced reduced' : Word α}
    (hraw : raw = raw') (hred : reduced = reduced')
    (step : FreeCancellationStep raw reduced) :
    (FreeCancellationStep.castWords hraw hred step).prefixLength =
      step.prefixLength := by
  cases hraw
  cases hred
  rfl

/-- Extending a cancellation step on the right does not move its selected
pair in the source word. -/
@[simp] theorem prefixLength_appendRight {α : Type*} {raw reduced : Word α}
    (step : FreeCancellationStep raw reduced) (suffix : Word α) :
    (step.appendRight suffix).prefixLength = step.prefixLength := by
  cases step with
  | cancel pre post a =>
      simp only [FreeCancellationStep.appendRight,
        FreeCancellationStep.prefixLength_castWords]
      simp [prefixLength]

/-- Adding a left context shifts the selected pair by the context length. -/
@[simp] theorem prefixLength_appendLeft {α : Type*} {raw reduced : Word α}
    (step : FreeCancellationStep raw reduced) (preContext : Word α) :
    (step.appendLeft preContext).prefixLength =
      preContext.length + step.prefixLength := by
  cases step with
  | cancel pre post a =>
      simp only [FreeCancellationStep.appendLeft,
        FreeCancellationStep.prefixLength_castWords]
      simp [prefixLength, List.length_append]

end FreeCancellationStep

namespace LabelledWalk

/-- A cancellation fold packages the exact source pair, its adjacent walk
positions, and the quotient replay state produced from that same pair. -/
structure CancellationFoldData {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {raw reduced : Word α}
    (step : FreeCancellationStep raw reduced)
    (walk : LabelledWalk G u v raw) where
  pair : LabelledDartPair G
  first_at : walk.occurrenceDarts[step.prefixLength]? = some pair.first
  second_at : walk.occurrenceDarts[step.prefixLength + 1]? = some pair.second
  adjacent : G.toDartGraph.target pair.first =
    G.toDartGraph.source pair.second
  result : WalkFoldResult G (u₀ := u) (v₀ := v) reduced

/-- Fold one adjacent inverse-letter pair in a labeled walk. This is the
combinatorial step used to realize a free cancellation as an edge fold. -/
noncomputable def foldCancellationWithPair {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {raw reduced : Word α}
    (step : FreeCancellationStep raw reduced)
    (walk : LabelledWalk G u v raw) :
    CancellationFoldData step walk := by
  cases step with
  | cancel pre post a =>
      have hword : (pre ++ [a] ++ [inverseLetter a] ++ post) =
          (pre ++ ([a] ++ ([inverseLetter a] ++ post))) := by
        simp [List.append_assoc]
      let walk' := hword ▸ walk
      let firstSplit := split pre ([a] ++ ([inverseLetter a] ++ post)) walk'
      let beforeVertex := firstSplit.1
      let before := firstSplit.2.1
      let afterBefore := firstSplit.2.2
      let secondSplit := split [a] ([inverseLetter a] ++ post) afterBefore
      let middleVertex := secondSplit.1
      let firstEdge := secondSplit.2.1
      let afterFirst := secondSplit.2.2
      let thirdSplit := split [inverseLetter a] post afterFirst
      let afterVertex := thirdSplit.1
      let secondEdge := thirdSplit.2.1
      let after := thirdSplit.2.2
      let firstData := edgeOf firstEdge
      let secondData := edgeOf secondEdge
      let firstDart := firstData.dart
      let secondDart := secondData.dart
      have hfirstSource := firstData.source_eq
      have hfirstTarget := firstData.target_eq
      have hfirstLabel := firstData.label_eq
      have hsecondSource := secondData.source_eq
      have hsecondTarget := secondData.target_eq
      have hsecondLabel := secondData.label_eq
      have hadjacent : G.toDartGraph.target firstDart =
          G.toDartGraph.source secondDart :=
        hfirstTarget.trans hsecondSource.symm
      have hlabels : G.label firstDart = inverseLetter (G.label secondDart) := by
        calc
          G.label firstDart = a := hfirstLabel
          _ = inverseLetter (G.label secondDart) := by
            rw [hsecondLabel, LabelledDartGraph.inverseLetter_inverse]
      let before' : LabelledWalk G u (G.toDartGraph.source firstDart) pre :=
        hfirstSource.symm ▸ before
      let after' : LabelledWalk G (G.toDartGraph.target secondDart) v post :=
        hsecondTarget ▸ after
      have hcast : walk.occurrenceDarts = walk'.occurrenceDarts :=
        (LabelledWalk.occurrenceDarts_cast hword walk).symm
      have hsplit₁ : walk'.occurrenceDarts =
          before.occurrenceDarts ++ afterBefore.occurrenceDarts :=
        LabelledWalk.occurrenceDarts_split pre
          ([a] ++ ([inverseLetter a] ++ post)) walk'
      have hsplit₂ : afterBefore.occurrenceDarts = firstEdge.occurrenceDarts ++
          afterFirst.occurrenceDarts :=
        LabelledWalk.occurrenceDarts_split [a] ([inverseLetter a] ++ post) afterBefore
      have hsplit₃ : afterFirst.occurrenceDarts = secondEdge.occurrenceDarts ++
          after.occurrenceDarts :=
        LabelledWalk.occurrenceDarts_split [inverseLetter a] post afterFirst
      have hfirstDarts : firstEdge.occurrenceDarts = [firstDart] :=
        LabelledWalk.occurrenceDarts_edgeOf firstEdge
      have hsecondDarts : secondEdge.occurrenceDarts = [secondDart] :=
        LabelledWalk.occurrenceDarts_edgeOf secondEdge
      have hlist : walk.occurrenceDarts = before.occurrenceDarts ++
          ([firstDart, secondDart] ++ after.occurrenceDarts) := by
        calc
          walk.occurrenceDarts = walk'.occurrenceDarts := hcast
          _ = before.occurrenceDarts ++ afterBefore.occurrenceDarts := hsplit₁
          _ = before.occurrenceDarts ++
              (firstEdge.occurrenceDarts ++ afterFirst.occurrenceDarts) := by
            rw [hsplit₂]
          _ = before.occurrenceDarts ++
              ([firstDart] ++ ([secondDart] ++ after.occurrenceDarts)) := by
            rw [hsplit₃, hfirstDarts, hsecondDarts]
          _ = before.occurrenceDarts ++ ([firstDart, secondDart] ++
              after.occurrenceDarts) := by simp
      have hbeforeLen : before.occurrenceDarts.length = pre.length := by
        rw [LabelledWalk.occurrenceDarts_length]
      have hfirstAt : walk.occurrenceDarts[pre.length]? = some firstDart := by
        rw [hlist]
        have hindex : pre.length = before.occurrenceDarts.length + 0 := by omega
        rw [hindex, List.getElem?_append_right (by omega)]
        simp
      have hsecondAt : walk.occurrenceDarts[pre.length + 1]? = some secondDart := by
        rw [hlist]
        have hindex : pre.length + 1 = before.occurrenceDarts.length + 1 := by omega
        rw [hindex, List.getElem?_append_right (by omega)]
        simp
      refine ⟨⟨firstDart, secondDart, hlabels⟩, hfirstAt, hsecondAt,
        hadjacent,
        ⟨G.folded α firstDart secondDart hlabels,
          LabelledGraphHom.fold G firstDart secondDart hlabels, ?_, ?_⟩⟩
      · exact before'.spliceAcrossFold firstDart secondDart after' hlabels
      · exact LabelledGraphHom.fold_mapDart_surjective G
          firstDart secondDart hlabels

/-- The replay state of one adjacent inverse-letter cancellation. -/
noncomputable def foldCancellation {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {raw reduced : Word α}
    (step : FreeCancellationStep raw reduced)
    (walk : LabelledWalk G u v raw) :
    WalkFoldResult G (u₀ := u) (v₀ := v) reduced :=
  (foldCancellationWithPair step walk).result

/-- The one-step replay graph is the quotient by the pair exposed alongside
the replay state. -/
theorem foldCancellationWithPair_graph {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {raw reduced : Word α}
    (step : FreeCancellationStep raw reduced)
    (walk : LabelledWalk G u v raw) :
    (foldCancellationWithPair step walk).result.graph =
      G.folded α (foldCancellationWithPair step walk).pair.first
        (foldCancellationWithPair step walk).pair.second
        (foldCancellationWithPair step walk).pair.inverse_labels := by
  cases step with
  | cancel pre post a => rfl

/-- The replay map sends the selected second dart to the reverse of the
selected first dart in its quotient graph. -/
theorem foldCancellationWithPair_pair_reverse {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {raw reduced : Word α}
    (step : FreeCancellationStep raw reduced)
    (walk : LabelledWalk G u v raw) :
    (foldCancellationWithPair step walk).result.hom.mapDart
        (foldCancellationWithPair step walk).pair.second =
      (foldCancellationWithPair step walk).result.graph.toDartGraph.reverse
        ((foldCancellationWithPair step walk).result.hom.mapDart
          (foldCancellationWithPair step walk).pair.first) := by
  cases step with
  | cancel pre post a =>
      exact LabelledDartPairFoldResult.oneFold_pair_reverse
        (foldCancellationWithPair (FreeCancellationStep.cancel pre post a) walk).pair

/-- Replay a sequence of adjacent free cancellations as successive graph
folds. The returned homomorphism tracks the original graph into the final
quotient, and the remaining boundary walk spells the reduced word. -/
noncomputable def foldSequence {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {raw reduced : Word α}
    (steps : FreeCancellationSequence raw reduced)
    (walk : LabelledWalk G u v raw) : WalkFoldResult G (u₀ := u) (v₀ := v) reduced :=
  match steps with
  | .refl _ => ⟨G, LabelledGraphHom.id G, walk, by
      intro d
      exact ⟨d, rfl⟩⟩
  | .cons step rest =>
      let first := foldCancellation step walk
      let later := foldSequence rest first.walk
      ⟨later.graph, LabelledGraphHom.comp later.hom first.hom, later.walk, by
        intro d
        obtain ⟨middle, hmiddle⟩ := later.hom_surjective d
        obtain ⟨original, horiginal⟩ := first.hom_surjective middle
        exact ⟨original, by simp [LabelledGraphHom.comp, hmiddle, horiginal]⟩⟩

/-- Every certified free reduction of a boundary word can be realized by a
finite sequence of labeled edge folds. -/
noncomputable def foldFreeReduction {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {raw reduced : Word α}
    (shape : FreeReductionShape raw reduced)
    (walk : LabelledWalk G u v raw) :
    WalkFoldResult G (u₀ := u) (v₀ := v) reduced :=
  foldSequence shape.to_cancellationSequence walk

end LabelledWalk

namespace WalkFoldResult

/-- First identify any selected inverse-labeled occurrence pairs, then replay
the boundary's adjacent cancellation trace in the resulting quotient graph. -/
noncomputable def foldPairsThenReduce {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} {raw reduced : Word α}
    (pairs : List (LabelledDartPair G))
    (steps : FreeCancellationSequence raw reduced)
    (walk : LabelledWalk G u v raw) :
    WalkFoldResult G (u₀ := u) (v₀ := v) reduced := by
  let paired := foldPairs pairs walk
  let reducedState := LabelledWalk.foldSequence steps paired.walk
  exact ⟨reducedState.graph,
    LabelledGraphHom.comp reducedState.hom paired.hom,
    reducedState.walk, by
      intro d
      obtain ⟨middle, hmiddle⟩ := reducedState.hom_surjective d
      obtain ⟨original, horiginal⟩ := paired.hom_surjective middle
      exact ⟨original, by simp [LabelledGraphHom.comp, hmiddle, horiginal]⟩⟩

/-- Later adjacent-cancellation folds preserve the opposite orientation of
every occurrence pair already folded in the source graph. -/
theorem foldPairsThenReduce_pair_reverse {α : Type*}
    {G : LabelledDartGraph α} {u v : G.toDartGraph.Vertex}
    {raw reduced : Word α}
    (pairs : List (LabelledDartPair G))
    (steps : FreeCancellationSequence raw reduced)
    (walk : LabelledWalk G u v raw) (pair : LabelledDartPair G)
    (hpair : pair ∈ pairs) :
    (foldPairsThenReduce pairs steps walk).hom.mapDart pair.second =
      (foldPairsThenReduce pairs steps walk).graph.toDartGraph.reverse
        ((foldPairsThenReduce pairs steps walk).hom.mapDart pair.first) := by
  let paired := foldPairs pairs walk
  let reducedState := LabelledWalk.foldSequence steps paired.walk
  have hfolded := foldPairs_pair_reverse pairs walk pair hpair
  change (LabelledGraphHom.comp reducedState.hom paired.hom).mapDart pair.second =
    reducedState.graph.toDartGraph.reverse
      ((LabelledGraphHom.comp reducedState.hom paired.hom).mapDart pair.first)
  calc
    _ = reducedState.hom.mapDart (paired.hom.mapDart pair.second) := rfl
    _ = reducedState.hom.mapDart
          (paired.graph.toDartGraph.reverse (paired.hom.mapDart pair.first)) :=
      congrArg reducedState.hom.mapDart hfolded
    _ = _ := (reducedState.hom.map_reverse _).symm

end WalkFoldResult

namespace LabelledWalk

/-- A walk with empty label has equal endpoints. -/
theorem endpoints_eq_of_empty {α : Type*} {G : LabelledDartGraph α}
    {u v : G.toDartGraph.Vertex} (walk : LabelledWalk G u v []) : u = v := by
  cases walk with
  | nil x => rfl

/-- A freely null labeled loop has its endpoints identified by the successive
edge folds obtained from its cancellation certificate. -/
theorem foldFreeReduction_identifiesEndpoints {α : Type*}
    {G : LabelledDartGraph α} {u v : G.toDartGraph.Vertex}
    {raw : Word α} (shape : FreeReductionShape raw [])
    (walk : LabelledWalk G u v raw) :
    (foldFreeReduction shape walk).hom.mapVertex u =
      (foldFreeReduction shape walk).hom.mapVertex v := by
  exact endpoints_eq_of_empty (foldFreeReduction shape walk).walk

/-- The same endpoint-identification result follows directly from equality to
the identity in the free group. -/
theorem foldFreeGroupIdentity_identifiesEndpoints {α : Type*}
    [DecidableEq α] {G : LabelledDartGraph α} {u v : G.toDartGraph.Vertex}
    {raw : Word α} (h : FreeGroup.mk raw = 1)
    (walk : LabelledWalk G u v raw) :
    (foldFreeReduction (FreeReductionShape.of_mk_eq_one h) walk).hom.mapVertex u =
      (foldFreeReduction (FreeReductionShape.of_mk_eq_one h) walk).hom.mapVertex v :=
  foldFreeReduction_identifiesEndpoints _ walk

end LabelledWalk

/-- A directed walk recorded by its dart sequence and endpoint equations. -/
inductive DartWalk (G : DartGraph) : G.Vertex → G.Vertex → Type where
  | nil (v : G.Vertex) : DartWalk G v v
  | cons {u v w : G.Vertex} (d : G.Dart)
      (source_eq : G.source d = u) (target_eq : G.target d = v)
      (tail : DartWalk G v w) : DartWalk G u w

namespace DartWalk

/-- Map a walk into the edge-fold quotient graph. -/
def foldMap {G : DartGraph} {u v : G.Vertex}
    (walk : DartWalk G u v) (a b : G.Dart) :
    DartWalk (DartGraph.foldedGraph G a b)
      (Quotient.mk (VertexFoldSetoid G a b) u)
      (Quotient.mk (VertexFoldSetoid G a b) v) :=
  match walk with
  | .nil x => .nil _
  | .cons d hsource htarget tail =>
      .cons (Quotient.mk (EdgeFoldSetoid G.reverse a b) d)
        (congrArg (Quotient.mk (VertexFoldSetoid G a b)) hsource)
        (congrArg (Quotient.mk (VertexFoldSetoid G a b)) htarget)
        (foldMap tail a b)

/-- Folding two oppositely traversed consecutive boundary darts identifies the
outer endpoints, so deleting that backtrack leaves a walk in the quotient. -/
def fold_cancel_backtrack {G : DartGraph} {v : G.Vertex}
    (a b : G.Dart) (tail : DartWalk G (G.target b) v) :
    DartWalk (DartGraph.foldedGraph G a b)
      (Quotient.mk (VertexFoldSetoid G a b) (G.source a))
      (Quotient.mk (VertexFoldSetoid G a b) v) := by
  exact (DartGraph.foldedEndpointEq G a b).symm ▸ tail.foldMap a b

end DartWalk

end GreendlingerDehn
