import Mathlib.Logic.Relation
import Mathlib.Logic.Function.Basic

namespace GreendlingerDehn

/-- The generating identifications for folding two oppositely traversed
boundary darts `a` and `b`: identify `a` with the reverse of `b`, and identify
their reverses as well. -/
def EdgeFoldGenerator {D : Type*} (reverse : D → D) (a b : D)
    (x y : D) : Prop :=
  (x = a ∧ y = reverse b) ∨ (x = reverse a ∧ y = b)

theorem EdgeFoldGenerator.reverse_compatible {D : Type*}
    {reverse : D → D} (hinvolutive : Function.Involutive reverse)
    {a b x y : D} (h : EdgeFoldGenerator reverse a b x y) :
    EdgeFoldGenerator reverse a b (reverse x) (reverse y) := by
  rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · exact Or.inr ⟨rfl, hinvolutive b⟩
  · exact Or.inl ⟨hinvolutive a, rfl⟩

/-- The equivalence relation generated by one boundary-edge fold. -/
def EdgeFoldSetoid {D : Type*} (reverse : D → D) (a b : D) : Setoid D :=
  Relation.EqvGen.setoid (EdgeFoldGenerator reverse a b)

/-- Darts after identifying the two boundary edges in an edge fold. -/
abbrev FoldedDart {D : Type*} (reverse : D → D) (a b : D) :=
  Quotient (EdgeFoldSetoid reverse a b)

/-- The edge-reversal involution descends through a boundary fold. -/
def foldedReverse {D : Type*} {reverse : D → D} (a b : D)
    (hinvolutive : Function.Involutive reverse) :
    FoldedDart reverse a b → FoldedDart reverse a b :=
  Quotient.lift (fun d => Quotient.mk (EdgeFoldSetoid reverse a b) (reverse d))
    (by
      intro x y hxy
      exact Quotient.sound <| by
        induction hxy with
        | rel x y h =>
            exact (Relation.EqvGen.rel _ _
              (EdgeFoldGenerator.reverse_compatible hinvolutive h))
        | refl x => exact Relation.EqvGen.refl _
        | symm x y _ ih => exact Relation.EqvGen.symm _ _ ih
        | trans x y z _ _ hxy hyz => exact Relation.EqvGen.trans _ _ _ hxy hyz)

@[simp]
theorem foldedReverse_mk {D : Type*} {reverse : D → D} (a b : D)
    (hinvolutive : Function.Involutive reverse) (d : D) :
    foldedReverse a b hinvolutive
        (Quotient.mk (EdgeFoldSetoid reverse a b) d) =
      Quotient.mk (EdgeFoldSetoid reverse a b) (reverse d) := rfl

theorem foldedReverse_involutive {D : Type*} {reverse : D → D}
    (a b : D) (hinvolutive : Function.Involutive reverse) :
    Function.Involutive (foldedReverse a b hinvolutive) := by
  intro d
  refine Quotient.inductionOn d ?_
  intro x
  simp only [foldedReverse_mk]
  rw [hinvolutive x]

/-- The two folded boundary darts become opposite orientations of one edge. -/
theorem fold_boundary_darts_eq_reverse {D : Type*} (reverse : D → D)
    (a b : D) :
    (Quotient.mk (EdgeFoldSetoid reverse a b) a : FoldedDart reverse a b) =
      Quotient.mk (EdgeFoldSetoid reverse a b) (reverse b) := by
  apply Quotient.sound
  exact Relation.EqvGen.rel _ _ (Or.inl ⟨rfl, rfl⟩)

/-- Reversal transports the first fold equality to the matching equality for
the twin darts, so a later fold can be composed with this quotient. -/
theorem fold_twin_darts_eq {D : Type*} {reverse : D → D}
    (a b : D) (_hinvolutive : Function.Involutive reverse) :
    (Quotient.mk (EdgeFoldSetoid reverse a b) (reverse a) :
        FoldedDart reverse a b) =
      Quotient.mk (EdgeFoldSetoid reverse a b) b := by
  apply Quotient.sound
  exact Relation.EqvGen.rel _ _ (Or.inr ⟨rfl, rfl⟩)

end GreendlingerDehn
