import Mathlib.Logic.Relation
import Mathlib.Data.Fintype.Card

namespace GreendlingerDehn

/-- The one-pair relation that identifies `x` and `y`. -/
def PairCollapseGenerator {α : Type*} (x y : α) (a b : α) : Prop :=
  (a = x ∧ b = y) ∨ (a = y ∧ b = x)

/-- The equivalence relation generated by one pair of distinct elements. -/
def PairCollapseSetoid {α : Type*} (x y : α) : Setoid α :=
  Relation.EqvGen.setoid (PairCollapseGenerator x y)

/-- Collapsing one pair in a finite type is equivalent to removing either one
of the two representatives from that type. -/
noncomputable def pairCollapseEquivSubtype {α : Type*} [Fintype α]
    (x y : α) (hxy : x ≠ y) :
    Quotient (PairCollapseSetoid x y) ≃ {a : α // a ≠ y} := by
  classical
  let collapse : α → {a : α // a ≠ y} := fun a =>
    ⟨if a = y then x else a, by
      by_cases ha : a = y
      · subst a
        simpa using hxy
      · simp [ha]⟩
  have hrespects : ∀ {a b}, PairCollapseGenerator x y a b → collapse a = collapse b := by
    intro a b h
    rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;>
      simp [collapse, hxy]
  let toSub : Quotient (PairCollapseSetoid x y) → {a : α // a ≠ y} :=
    Quotient.lift collapse (by
      intro a b hab
      change Relation.EqvGen (PairCollapseGenerator x y) a b at hab
      induction hab with
      | rel a b h => exact hrespects h
      | refl a => rfl
      | symm a b _ ih => exact ih.symm
      | trans a b c _ _ ih₁ ih₂ => exact ih₁.trans ih₂)
  refine ⟨toSub, fun a => Quotient.mk _ a.1, ?_, ?_⟩
  · intro q
    refine Quotient.inductionOn q ?_
    intro a
    by_cases ha : a = y
    · subst a
      change Quotient.mk (PairCollapseSetoid x y) (collapse y).1 =
        Quotient.mk (PairCollapseSetoid x y) y
      simp only [collapse]
      apply Quotient.sound
      exact Relation.EqvGen.rel _ _ (Or.inl ⟨rfl, rfl⟩)
    · simp [toSub, collapse, ha]
  · intro a
    apply Subtype.ext
    have h : a.1 ≠ y := a.property
    simp [toSub, collapse, h]

/-- A finite quotient by one genuinely new pair loses exactly one element. The
quotient's `Fintype` instance is explicit because the relation need not be
decidable. -/
theorem pairCollapse_quotient_card {α : Type*} [Fintype α]
    (x y : α) (hxy : x ≠ y)
    [Fintype (Quotient (PairCollapseSetoid x y))] :
    Fintype.card (Quotient (PairCollapseSetoid x y)) + 1 = Fintype.card α := by
  classical
  rw [Fintype.card_congr (pairCollapseEquivSubtype x y hxy)]
  have hcomp := Fintype.card_subtype_compl (fun a : α => a = y)
  have hsingle : Fintype.card {a : α // a = y} = 1 := by simp
  rw [hsingle] at hcomp
  rw [hcomp]
  exact Nat.sub_add_cancel (Nat.succ_le_iff.mpr
    (Fintype.card_pos_iff.mpr ⟨y⟩))

end GreendlingerDehn
