import SmallCancellation.PairFoldCellLink
import SmallCancellation.PairingComponents

namespace GreendlingerDehn

/-- The cyclic polygon-corner involution, viewed as a total pairing of the
face-endpoint germs at one quotient vertex. -/
noncomputable def MinimalAreaRelatorBoundarySeed.pairFoldCornerPairingAtVertex
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex} :
    PartialOccurrencePairing (seed.PairFoldFaceGermsAtVertex hne v) where
  partner a := some (seed.pairFoldFaceCornerMateAtVertex hne a)
  partner_symm := by
    intro a b hab
    have hb : seed.pairFoldFaceCornerMateAtVertex hne a = b :=
      Option.some.inj hab
    subst b
    simpa using seed.pairFoldFaceCornerMateAtVertex_involutive hne a
  partner_ne := by
    intro a hself
    have heq : seed.pairFoldFaceCornerMateAtVertex hne a = a :=
      Option.some.inj hself
    exact seed.pairFoldFaceCornerMateAtVertex_ne hne a heq

/-- Crossing a folded edge is a partial pairing on face-endpoint germs; the
unpaired germs are precisely the ends exposed to the boundary. -/
noncomputable def MinimalAreaRelatorBoundarySeed.pairFoldEdgePairingAtVertex
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex} :
    PartialOccurrencePairing (seed.PairFoldFaceGermsAtVertex hne v) where
  partner := seed.pairFoldFaceEdgeMateAtVertex? hne
  partner_symm := by
    intro a b hab
    exact seed.pairFoldFaceEdgeMateAtVertex?_involutive hne a b hab
  partner_ne := by
    intro a hself
    have hstep := seed.pairFoldFaceEdgeMateAtVertex?_spec hne a a hself
    exact hstep.2 rfl

/-- The flag graph of corners and shared-edge crossings is exactly the graph
generated by these two pairings. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldFaceLinkGraph_eq_pairingGraph
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex} :
    seed.pairFoldFaceLinkGraph hne v =
      twoPairingGraph (seed.pairFoldCornerPairingAtVertex hne)
        (seed.pairFoldEdgePairingAtVertex hne) := by
  classical
  ext a b
  rw [seed.pairFoldFaceLinkGraph_adj_iff hne v a b]
  simp only [twoPairingGraph, MinimalAreaRelatorBoundarySeed.pairFoldCornerPairingAtVertex,
    MinimalAreaRelatorBoundarySeed.pairFoldEdgePairingAtVertex,
    PartialOccurrencePairing.partner, Option.some.injEq]
  constructor
  · rintro (hcorner | hedge)
    · exact Or.inl hcorner
    · exact Or.inr
        (seed.pairFoldFaceEdgeMateAtVertex?_of_edgeStep hne a b hedge)
  · rintro (hcorner | hedge)
    · exact Or.inl hcorner
    · exact Or.inr
        (seed.pairFoldFaceEdgeMateAtVertex?_spec hne a b hedge)

/-- Two face germs at one quotient vertex name the same oriented edge end
exactly when they are equal or they are paired across that folded edge. This
identifies the transition pairing's vertex quotient with the actual edge-end
vertices of the corner-incidence multigraph. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldFaceGermOutDart_eq_iff
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (a b : seed.PairFoldFaceGermsAtVertex hne v) :
    seed.pairFoldFaceGermOutDart hne a =
        seed.pairFoldFaceGermOutDart hne b ↔
      a = b ∨ seed.PairFoldFaceEdgeStepAtVertex hne a b := by
  classical
  constructor
  · intro heq
    rcases a with ⟨⟨sideA, endpointA⟩, hvA⟩
    rcases b with ⟨⟨sideB, endpointB⟩, hvB⟩
    have hclassOut := congrArg
      (fun d => seed.pairFoldCellLinkDartEdgeClass d) heq
    have hclass : seed.pairFoldIncidenceEdgeClass (Sum.inl sideA) =
        seed.pairFoldIncidenceEdgeClass (Sum.inl sideB) := by
      calc
        _ = seed.pairFoldCellLinkDartEdgeClass
            (seed.pairFoldFaceGermOutDart hne ⟨(sideA, endpointA), hvA⟩) :=
          (seed.pairFoldFaceGermOutDart_edgeClass hne
            ⟨(sideA, endpointA), hvA⟩).symm
        _ = seed.pairFoldCellLinkDartEdgeClass
            (seed.pairFoldFaceGermOutDart hne ⟨(sideB, endpointB), hvB⟩) := hclassOut
        _ = _ := seed.pairFoldFaceGermOutDart_edgeClass hne
          ⟨(sideB, endpointB), hvB⟩
    have hDart := congrArg Subtype.val heq
    by_cases hside : sideA = sideB
    · subst sideB
      cases endpointA <;> cases endpointB
      · left
        apply Subtype.ext
        rfl
      · have hfixed :
            seed.pairFoldFiniteGraph.toDartGraph.reverse
                (seed.pairFoldFaceGermOutDart hne ⟨(sideA, false), hvA⟩).1 =
              (seed.pairFoldFaceGermOutDart hne ⟨(sideA, false), hvA⟩).1 := by
          change seed.pairFoldFiniteGraph.toDartGraph.reverse
              (seed.pairFoldFiniteGraph.toDartGraph.reverse
                (seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA))) = _
          calc
            _ = seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA) :=
              seed.pairFoldFiniteGraph.toDartGraph.reverse_involutive _
            _ = seed.pairFoldFiniteGraph.toDartGraph.reverse
                (seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA)) := hDart.symm
        exact False.elim ((seed.pairFoldFiniteGraph_reverse_ne hne
          (seed.pairFoldFaceGermOutDart hne ⟨(sideA, false), hvA⟩)) hfixed)
      · have hfixed :
            seed.pairFoldFiniteGraph.toDartGraph.reverse
                (seed.pairFoldFaceGermOutDart hne ⟨(sideA, true), hvA⟩).1 =
              (seed.pairFoldFaceGermOutDart hne ⟨(sideA, true), hvA⟩).1 := by
          change seed.pairFoldFiniteGraph.toDartGraph.reverse
              (seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA)) = _
          exact hDart.symm
        exact False.elim ((seed.pairFoldFiniteGraph_reverse_ne hne
          (seed.pairFoldFaceGermOutDart hne ⟨(sideA, true), hvA⟩)) hfixed)
      · left
        apply Subtype.ext
        rfl
    · have hshare : seed.PairFoldFaceSidesShareEdge sideA sideB :=
        ⟨hside, hclass⟩
      let edge := seed.pairFoldIncidenceEdgeClass (Sum.inl sideA)
      let incA : seed.PairFoldIncidenceFiber edge := ⟨Sum.inl sideA, rfl⟩
      let incB : seed.PairFoldIncidenceFiber edge := ⟨Sum.inl sideB, hclass.symm⟩
      have hab : incA ≠ incB := by
        intro heq
        apply hside
        exact Sum.inl.inj (congrArg Subtype.val heq)
      have hop := seed.pairFoldFiniteIncidenceDart_opposite_of_ne
        hne edge incA incB hab
      have hop' :
          seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideB) =
            seed.pairFoldFiniteGraph.toDartGraph.reverse
              (seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA)) := by
        simpa [incA, incB, edge] using hop
      cases endpointA <;> cases endpointB
      · have hself :
            seed.pairFoldFiniteGraph.toDartGraph.reverse
                (seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA)) =
              seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA) := by
          have hDart' :
              seed.pairFoldFiniteGraph.toDartGraph.reverse
                  (seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA)) =
                seed.pairFoldFiniteGraph.toDartGraph.reverse
                  (seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideB)) := by
            simpa [MinimalAreaRelatorBoundarySeed.pairFoldFaceGermOutDart] using hDart
          rw [hop'] at hDart'
          rw [seed.pairFoldFiniteGraph.toDartGraph.reverse_involutive] at hDart'
          exact hDart'
        have hfixed :
            seed.pairFoldFiniteGraph.toDartGraph.reverse
                (seed.pairFoldFaceGermOutDart hne ⟨(sideA, false), hvA⟩).1 =
              (seed.pairFoldFaceGermOutDart hne ⟨(sideA, false), hvA⟩).1 := by
          change seed.pairFoldFiniteGraph.toDartGraph.reverse
              (seed.pairFoldFiniteGraph.toDartGraph.reverse
                (seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA))) = _
          rw [seed.pairFoldFiniteGraph.toDartGraph.reverse_involutive]
          exact hself.symm
        exact False.elim ((seed.pairFoldFiniteGraph_reverse_ne hne
          (seed.pairFoldFaceGermOutDart hne ⟨(sideA, false), hvA⟩)) hfixed)
      · have hstep : seed.PairFoldFaceEdgeStepAtVertex hne
            ⟨(sideA, false), hvA⟩ ⟨(sideB, true), hvB⟩ := by
          change seed.PairFoldFaceSidesShareEdge sideA sideB ∧ false ≠ true
          exact ⟨hshare, by decide⟩
        exact Or.inr hstep
      · have hstep : seed.PairFoldFaceEdgeStepAtVertex hne
            ⟨(sideA, true), hvA⟩ ⟨(sideB, false), hvB⟩ := by
          change seed.PairFoldFaceSidesShareEdge sideA sideB ∧ true ≠ false
          exact ⟨hshare, by decide⟩
        exact Or.inr hstep
      · have hself :
            seed.pairFoldFiniteGraph.toDartGraph.reverse
                (seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA)) =
              seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA) := by
          have hDart' :
              seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA) =
                seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideB) := by
            simpa [MinimalAreaRelatorBoundarySeed.pairFoldFaceGermOutDart] using hDart
          rw [hop'] at hDart'
          exact hDart'.symm
        have hfixed :
            seed.pairFoldFiniteGraph.toDartGraph.reverse
                (seed.pairFoldFaceGermOutDart hne ⟨(sideA, true), hvA⟩).1 =
              (seed.pairFoldFaceGermOutDart hne ⟨(sideA, true), hvA⟩).1 := by
          change seed.pairFoldFiniteGraph.toDartGraph.reverse
              (seed.pairFoldFiniteIncidenceDart hne (Sum.inl sideA)) = _
          exact hself
        exact False.elim ((seed.pairFoldFiniteGraph_reverse_ne hne
          (seed.pairFoldFaceGermOutDart hne ⟨(sideA, true), hvA⟩)) hfixed)
  · rintro (hab | hedge)
    · cases hab
      rfl
    · exact seed.pairFoldFaceGermOutDart_eq_of_edgeStep hne a b hedge

/-- A corner transition and a folded-edge transition cannot leave a germ
through the same oriented edge end. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldFaceEdgeMateAtVertex?_ne_cornerMate
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (germ : seed.PairFoldFaceGermsAtVertex hne v) :
    seed.pairFoldFaceEdgeMateAtVertex? hne germ ≠
      some (seed.pairFoldFaceCornerMateAtVertex hne germ) := by
  intro h
  have hstep := seed.pairFoldFaceEdgeMateAtVertex?_spec hne germ
    (seed.pairFoldFaceCornerMateAtVertex hne germ) h
  have hout := seed.pairFoldFaceGermOutDart_eq_of_edgeStep hne germ
    (seed.pairFoldFaceCornerMateAtVertex hne germ) hstep
  exact seed.pairFoldFaceGermOutDart_ne_cornerMate hne germ hout

/-- The simple graph obtained by forgetting parallel occurrences from the
actual corner-incidence link. Its edges join the oriented edge ends at one
relator corner. -/
noncomputable def MinimalAreaRelatorBoundarySeed.pairFoldCellLinkCornerAdjacencyAtVertex
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    (v : seed.pairFoldFiniteGraph.toDartGraph.Vertex) :
    SimpleGraph (seed.PairFoldVertexLinkDart hne v) :=
  SimpleGraph.fromRel fun a b =>
    ∃ germ : seed.PairFoldFaceGermsAtVertex hne v,
      a = seed.pairFoldFaceGermOutDart hne germ ∧
        b = seed.pairFoldFaceGermOutDart hne
          (seed.pairFoldFaceCornerMateAtVertex hne germ)

/-- Each transition in a face-germ component maps either to equality of actual
edge ends (across a shared edge) or to an edge of the corner-adjacency graph
(around a polygon corner). -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldCellLinkComponent_output_darts_reachable
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (C : (twoPairingGraph (seed.pairFoldCornerPairingAtVertex hne (v := v))
      (seed.pairFoldEdgePairingAtVertex hne (v := v))).ConnectedComponent)
    (a b : C.supp) :
    (seed.pairFoldCellLinkCornerAdjacencyAtVertex hne v).Reachable
      (seed.pairFoldFaceGermOutDart hne a.1)
      (seed.pairFoldFaceGermOutDart hne b.1) := by
  classical
  let G := seed.pairFoldCellLinkCornerAdjacencyAtVertex hne v
  have hreach : (seed.pairFoldFaceLinkGraph hne v).Reachable a.1 b.1 := by
    rw [seed.pairFoldFaceLinkGraph_eq_pairingGraph hne]
    exact SimpleGraph.ConnectedComponent.reachable_of_mem_supp C a.2 b.2
  have hstep : ∀ {x y : seed.PairFoldFaceGermsAtVertex hne v},
      (seed.pairFoldFaceLinkGraph hne v).Adj x y →
        Relation.ReflTransGen G.Adj
          (seed.pairFoldFaceGermOutDart hne x)
          (seed.pairFoldFaceGermOutDart hne y) := by
    intro x y hadj
    rcases (seed.pairFoldFaceLinkGraph_adj_iff hne v x y).mp hadj with
      hcorner | hedge
    · subst y
      have hcornerAdj : G.Adj
          (seed.pairFoldFaceGermOutDart hne x)
          (seed.pairFoldFaceGermOutDart hne
            (seed.pairFoldFaceCornerMateAtVertex hne x)) := by
        apply (SimpleGraph.fromRel_adj _ _ _).2
        exact ⟨seed.pairFoldFaceGermOutDart_ne_cornerMate hne x,
          Or.inl ⟨x, rfl, rfl⟩⟩
      exact Relation.ReflTransGen.single hcornerAdj
    · have hsame := seed.pairFoldFaceGermOutDart_eq_of_edgeStep hne x y hedge
      rw [hsame]
  have hmap : ∀ {x y : seed.PairFoldFaceGermsAtVertex hne v},
      Relation.ReflTransGen (seed.pairFoldFaceLinkGraph hne v).Adj x y →
        Relation.ReflTransGen G.Adj
          (seed.pairFoldFaceGermOutDart hne x)
          (seed.pairFoldFaceGermOutDart hne y) := by
    intro x y hxy
    induction hxy with
    | refl => exact Relation.ReflTransGen.refl
    | @tail y z hxy hyz ih => exact ih.trans (hstep hyz)
  have hsequence :=
    (seed.pairFoldFaceLinkGraph hne v).reachable_iff_reflTransGen _ _ |>.mp hreach
  have hmapped := hmap hsequence
  exact (G.reachable_iff_reflTransGen _ _).2 hmapped

/-- The edge-end image of one face-germ transition component is exactly the
support of its connected component in the simple corner-adjacency graph. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldCellLinkComponent_output_image_eq_component_support
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (C : (twoPairingGraph (seed.pairFoldCornerPairingAtVertex hne (v := v))
      (seed.pairFoldEdgePairingAtVertex hne (v := v))).ConnectedComponent)
    (base : C.supp) :
    {d | ∃ germ : C.supp,
      seed.pairFoldFaceGermOutDart hne germ.1 = d} =
      ((seed.pairFoldCellLinkCornerAdjacencyAtVertex hne v).connectedComponentMk
        (seed.pairFoldFaceGermOutDart hne base.1)).supp := by
  classical
  let G := seed.pairFoldCellLinkCornerAdjacencyAtVertex hne v
  have hsame_output_mem (germ₁ germ₂ : seed.PairFoldFaceGermsAtVertex hne v)
      (hmem : germ₁ ∈ C.supp)
      (houtputs : seed.pairFoldFaceGermOutDart hne germ₁ =
        seed.pairFoldFaceGermOutDart hne germ₂) : germ₂ ∈ C.supp := by
    rcases (seed.pairFoldFaceGermOutDart_eq_iff hne germ₁ germ₂).mp houtputs with
      heq | hedge
    · simpa [heq] using hmem
    · have hadj := seed.pairFoldFaceLinkGraph_edge_adj hne hedge
      rw [seed.pairFoldFaceLinkGraph_eq_pairingGraph hne] at hadj
      exact SimpleGraph.ConnectedComponent.mem_supp_of_adj_mem_supp C hmem hadj
  have hcorner_mem (germ : seed.PairFoldFaceGermsAtVertex hne v)
      (hmem : germ ∈ C.supp) :
      seed.pairFoldFaceCornerMateAtVertex hne germ ∈ C.supp := by
    have hadj := seed.pairFoldFaceLinkGraph_corner_adj hne germ
    rw [seed.pairFoldFaceLinkGraph_eq_pairingGraph hne] at hadj
    exact SimpleGraph.ConnectedComponent.mem_supp_of_adj_mem_supp C hmem hadj
  have hclosed : ∀ {d e : seed.PairFoldVertexLinkDart hne v},
      G.Adj d e →
        (∃ germ : C.supp, seed.pairFoldFaceGermOutDart hne germ.1 = d) →
        ∃ germ : C.supp, seed.pairFoldFaceGermOutDart hne germ.1 = e := by
    intro d e hadj hd
    change d ≠ e ∧
      ((∃ germ : seed.PairFoldFaceGermsAtVertex hne v,
          d = seed.pairFoldFaceGermOutDart hne germ ∧
            e = seed.pairFoldFaceGermOutDart hne
              (seed.pairFoldFaceCornerMateAtVertex hne germ)) ∨
        (∃ germ : seed.PairFoldFaceGermsAtVertex hne v,
          e = seed.pairFoldFaceGermOutDart hne germ ∧
            d = seed.pairFoldFaceGermOutDart hne
              (seed.pairFoldFaceCornerMateAtVertex hne germ))) at hadj
    rcases hd with ⟨current, hcurrent⟩
    rcases hadj.2 with ⟨germ, hsource, htarget⟩ | ⟨germ, htarget, hsource⟩
    · have hmem := hsame_output_mem current.1 germ current.2 (hcurrent.trans hsource)
      exact ⟨⟨seed.pairFoldFaceCornerMateAtVertex hne germ,
        hcorner_mem germ hmem⟩, htarget.symm⟩
    · have hmateMem := hsame_output_mem current.1
        (seed.pairFoldFaceCornerMateAtVertex hne germ) current.2
        (hcurrent.trans hsource)
      have hdouble := seed.pairFoldFaceCornerMateAtVertex_involutive hne germ
      have hgermMem := hcorner_mem
        (seed.pairFoldFaceCornerMateAtVertex hne germ) hmateMem
      rw [hdouble] at hgermMem
      exact ⟨⟨germ, hgermMem⟩, htarget.symm⟩
  have hclosed_reachable : ∀ {d e : seed.PairFoldVertexLinkDart hne v},
      Relation.ReflTransGen G.Adj d e →
        (∃ germ : C.supp, seed.pairFoldFaceGermOutDart hne germ.1 = d) →
        ∃ germ : C.supp, seed.pairFoldFaceGermOutDart hne germ.1 = e := by
    intro d e hreach hd
    induction hreach with
    | refl => exact hd
    | @tail e f hprev hlast ih => exact hclosed hlast ih
  ext d
  constructor
  · rintro ⟨germ, rfl⟩
    rw [SimpleGraph.ConnectedComponent.mem_supp_iff]
    change G.connectedComponentMk
      (seed.pairFoldFaceGermOutDart hne germ.1) =
        G.connectedComponentMk (seed.pairFoldFaceGermOutDart hne base.1)
    exact SimpleGraph.ConnectedComponent.sound
      (seed.pairFoldCellLinkComponent_output_darts_reachable hne C base germ).symm
  · intro hd
    have hbase : seed.pairFoldFaceGermOutDart hne base.1 ∈
        (G.connectedComponentMk
          (seed.pairFoldFaceGermOutDart hne base.1)).supp :=
      SimpleGraph.ConnectedComponent.connectedComponentMk_mem
    have hreach := SimpleGraph.ConnectedComponent.reachable_of_mem_supp
      (G.connectedComponentMk (seed.pairFoldFaceGermOutDart hne base.1)) hbase hd
    have hsequence := (G.reachable_iff_reflTransGen _ _).mp hreach
    exact hclosed_reachable hsequence ⟨base, rfl⟩

/-- At each face germ the actual link degree is one at an exposed edge end
and two when a second face is folded across that edge. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldFaceLinkGraph_degree_eq_one_or_two
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (a : seed.PairFoldFaceGermsAtVertex hne v) :
    ((seed.pairFoldFaceLinkGraph hne v).neighborFinset a).card = 1 ∨
      ((seed.pairFoldFaceLinkGraph hne v).neighborFinset a).card = 2 := by
  classical
  let G := seed.pairFoldFaceLinkGraph hne v
  let corner := seed.pairFoldFaceCornerMateAtVertex hne a
  have hcorner_mem : corner ∈ G.neighborFinset a := by
    exact (G.mem_neighborFinset (v := a) corner).2
      (seed.pairFoldFaceLinkGraph_corner_adj hne a)
  cases hmate : seed.pairFoldFaceEdgeMateAtVertex? hne a with
  | none =>
    have hneighbors : G.neighborFinset a = {corner} := by
      ext b
      constructor
      · intro hb
        have hadj := (G.mem_neighborFinset (v := a) b).1 hb
        rcases (seed.pairFoldFaceLinkGraph_adj_iff hne v a b).1 hadj with
          hcorner' | hedge
        · exact Finset.mem_singleton.mpr hcorner'.symm
        · have hmate' := seed.pairFoldFaceEdgeMateAtVertex?_of_edgeStep
            hne a b hedge
          rw [hmate] at hmate'
          simp at hmate'
      · intro hb
        have hb' : b = corner := Finset.mem_singleton.mp hb
        subst b
        exact hcorner_mem
    left
    rw [hneighbors]
    simp
  | some b =>
    have hb_ne_corner : b ≠ corner := by
      intro hbc
      subst b
      exact (seed.pairFoldFaceEdgeMateAtVertex?_ne_cornerMate hne a) hmate
    have hacross : G.Adj a b := by
      apply (seed.pairFoldFaceLinkGraph_adj_iff hne v a b).2
      exact Or.inr (seed.pairFoldFaceEdgeMateAtVertex?_spec hne a b hmate)
    have hneighbors : G.neighborFinset a = insert corner {b} := by
      ext c
      constructor
      · intro hc
        have hadj := (G.mem_neighborFinset (v := a) c).1 hc
        rcases (seed.pairFoldFaceLinkGraph_adj_iff hne v a c).1 hadj with
          hcorner' | hedge
        · exact Finset.mem_insert.mpr (Or.inl hcorner'.symm)
        · have hmate' := seed.pairFoldFaceEdgeMateAtVertex?_of_edgeStep
            hne a c hedge
          have hbc : b = c := Option.some.inj (hmate.symm.trans hmate')
          exact Finset.mem_insert.mpr (Or.inr
            (Finset.mem_singleton.mpr hbc.symm))
      · intro hc
        rcases Finset.mem_insert.mp hc with hcorner' | hb'
        · have hcorner'' : c = corner := hcorner'
          subst c
          exact hcorner_mem
        · have hbc : c = b := Finset.mem_singleton.mp hb'
          subst c
          exact (G.mem_neighborFinset (v := a) b).2 hacross
    right
    rw [hneighbors]
    simp [Ne.symm hb_ne_corner]

/-- Degree one is equivalent to being exposed to the boundary in the folded
complex. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldFaceLinkGraph_degree_eq_one_iff_edgeMate_none
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (a : seed.PairFoldFaceGermsAtVertex hne v) :
    ((seed.pairFoldFaceLinkGraph hne v).neighborFinset a).card = 1 ↔
      seed.pairFoldFaceEdgeMateAtVertex? hne a = none := by
  classical
  let G := seed.pairFoldFaceLinkGraph hne v
  let corner := seed.pairFoldFaceCornerMateAtVertex hne a
  have hcorner_mem : corner ∈ G.neighborFinset a := by
    exact (G.mem_neighborFinset (v := a) corner).2
      (seed.pairFoldFaceLinkGraph_corner_adj hne a)
  constructor
  · intro hdegree
    cases hmate : seed.pairFoldFaceEdgeMateAtVertex? hne a with
    | none => rfl
    | some b =>
      have hb_ne_corner : b ≠ corner := by
        intro hbc
        subst b
        exact (seed.pairFoldFaceEdgeMateAtVertex?_ne_cornerMate hne a) hmate
      have hacross : G.Adj a b := by
        apply (seed.pairFoldFaceLinkGraph_adj_iff hne v a b).2
        exact Or.inr (seed.pairFoldFaceEdgeMateAtVertex?_spec hne a b hmate)
      change (G.neighborFinset a).card = 1 at hdegree
      obtain ⟨c, hc⟩ := Finset.card_eq_one.mp hdegree
      change G.neighborFinset a = {c} at hc
      have hcorner_eq : corner = c := by
        rw [hc] at hcorner_mem
        exact Finset.mem_singleton.mp hcorner_mem
      have hb_eq : b = c := by
        have hmem : b ∈ G.neighborFinset a :=
          (G.mem_neighborFinset (v := a) b).2 hacross
        rw [hc] at hmem
        exact Finset.mem_singleton.mp hmem
      exact False.elim (hb_ne_corner (hb_eq.trans hcorner_eq.symm))
  · intro hnone
    cases hmate : seed.pairFoldFaceEdgeMateAtVertex? hne a with
    | none =>
      have hneighbors : G.neighborFinset a = {corner} := by
        ext b
        constructor
        · intro hb
          have hadj := (G.mem_neighborFinset (v := a) b).1 hb
          rcases (seed.pairFoldFaceLinkGraph_adj_iff hne v a b).1 hadj with
            hcorner' | hedge
          · exact Finset.mem_singleton.mpr hcorner'.symm
          · have hmate' := seed.pairFoldFaceEdgeMateAtVertex?_of_edgeStep
              hne a b hedge
            rw [hmate] at hmate'
            simp at hmate'
        · intro hb
          have hb' : b = corner := Finset.mem_singleton.mp hb
          subst b
          exact hcorner_mem
      rw [hneighbors]
      simp
    | some b =>
      rw [hmate] at hnone
      cases hnone

/-- Degree two is equivalent to having the unique across-edge partner. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldFaceLinkGraph_degree_eq_two_iff_edgeMate_isSome
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (a : seed.PairFoldFaceGermsAtVertex hne v) :
    ((seed.pairFoldFaceLinkGraph hne v).neighborFinset a).card = 2 ↔
      ∃ b, seed.pairFoldFaceEdgeMateAtVertex? hne a = some b := by
  constructor
  · intro hdegree
    by_contra hnot
    have hnone : seed.pairFoldFaceEdgeMateAtVertex? hne a = none := by
      cases hmate : seed.pairFoldFaceEdgeMateAtVertex? hne a with
      | none => exact rfl
      | some b => exact False.elim (hnot ⟨b, hmate⟩)
    have hone := (seed.pairFoldFaceLinkGraph_degree_eq_one_iff_edgeMate_none
      hne a).2 hnone
    omega
  · rintro ⟨b, hmate⟩
    rcases seed.pairFoldFaceLinkGraph_degree_eq_one_or_two hne a with hone | htwo
    · have hnone := (seed.pairFoldFaceLinkGraph_degree_eq_one_iff_edgeMate_none
        hne a).1 hone
      rw [hmate] at hnone
      cases hnone
    · exact htwo

/-- The degree of an actual corner-incidence link vertex is one exactly when
its incident face germ is exposed to the boundary. The endpoint-germ
equivalence identifies the multigraph's incidence fiber with the fiber of the
map from face germs to oriented edge ends. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldCellLinkAt_degree_eq_one_iff_edgeMate_none
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (germ : seed.PairFoldFaceGermsAtVertex hne v) :
    @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
      (seed.pairFoldFaceCornerAtVertexFintype hne v)
      (seed.pairFoldFaceGermOutDart hne germ)
      (seed.pairFoldCellLinkEndpointFiberFintype hne
        (seed.pairFoldFaceGermOutDart hne germ)) = 1 ↔
      seed.pairFoldFaceEdgeMateAtVertex? hne germ = none := by
  classical
  let d := seed.pairFoldFaceGermOutDart hne germ
  let endpointFiber := {endpoint : seed.PairFoldCellLinkEndpoint hne v //
    seed.pairFoldCellLinkEndpointDart hne endpoint = d}
  let germFiber := {other : seed.PairFoldFaceGermsAtVertex hne v //
    seed.pairFoldFaceGermOutDart hne other = d}
  letI : Fintype endpointFiber := seed.pairFoldCellLinkEndpointFiberFintype hne d
  letI : Fintype germFiber := seed.pairFoldFaceGermOutDartFiberFintype hne d
  have hcardFibers : Fintype.card endpointFiber = Fintype.card germFiber :=
    Fintype.card_congr (seed.pairFoldCellLinkEndpointFiberEquiv hne d)
  have hcardOne : Fintype.card germFiber = 1 ↔
      seed.pairFoldFaceEdgeMateAtVertex? hne germ = none := by
    have hle : Fintype.card germFiber ≤ 2 := by
      simpa only [germFiber, d] using
        seed.pairFoldFaceGermOutDart_fiber_card_le_two hne d
          ⟨germ, rfl⟩
    constructor
    · intro hone
      cases hmate : seed.pairFoldFaceEdgeMateAtVertex? hne germ with
      | none => rfl
      | some other =>
          have hstep := seed.pairFoldFaceEdgeMateAtVertex?_spec
            hne germ other hmate
          have hother : seed.pairFoldFaceGermOutDart hne other = d := by
            dsimp [d]
            exact (seed.pairFoldFaceGermOutDart_eq_of_edgeStep
              hne germ other hstep).symm
          have hneGerm : germ ≠ other := by
            intro heq
            apply hstep.2
            exact congrArg Prod.snd (congrArg Subtype.val heq)
          let pair : Fin 2 → germFiber := fun i =>
            if i.val = 0 then ⟨germ, rfl⟩ else ⟨other, hother⟩
          have hinj : Function.Injective pair := by
            intro i j hij
            fin_cases i <;> fin_cases j
            · rfl
            · exact False.elim (hneGerm (congrArg Subtype.val hij))
            · exact False.elim (hneGerm.symm (congrArg Subtype.val hij))
            · rfl
          have htwo : 2 ≤ Fintype.card germFiber := by
            have h := Fintype.card_le_of_injective pair hinj
            simpa [pair] using h
          omega
    · intro hnone
      have huniq : ∀ x : germFiber, x.1 = germ := by
        intro x
        have houtputs : seed.pairFoldFaceGermOutDart hne germ =
            seed.pairFoldFaceGermOutDart hne x.1 := by
          simpa [d] using x.2.symm
        rcases (seed.pairFoldFaceGermOutDart_eq_iff hne germ x.1).mp houtputs with
          heq | hedge
        · exact heq.symm
        · have hmate := seed.pairFoldFaceEdgeMateAtVertex?_of_edgeStep
            hne germ x.1 hedge
          rw [hnone] at hmate
          cases hmate
      apply Fintype.card_eq_one_iff.mpr
      refine ⟨⟨germ, rfl⟩, ?_⟩
      intro x
      apply Subtype.ext
      exact huniq x
  unfold FiniteIncidenceMultigraph.degree
  change Fintype.card endpointFiber = 1 ↔ _
  rw [hcardFibers]
  exact hcardOne

/-- Every edge end represented by a face germ has actual corner degree one or
two: one at an exposed end and two where a second face meets across the edge. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldCellLinkAt_degree_eq_one_or_two
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (germ : seed.PairFoldFaceGermsAtVertex hne v) :
    @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
      (seed.pairFoldFaceCornerAtVertexFintype hne v)
      (seed.pairFoldFaceGermOutDart hne germ)
      (seed.pairFoldCellLinkEndpointFiberFintype hne
        (seed.pairFoldFaceGermOutDart hne germ)) = 1 ∨
    @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
      (seed.pairFoldFaceCornerAtVertexFintype hne v)
      (seed.pairFoldFaceGermOutDart hne germ)
      (seed.pairFoldCellLinkEndpointFiberFintype hne
        (seed.pairFoldFaceGermOutDart hne germ)) = 2 := by
  classical
  cases hmate : seed.pairFoldFaceEdgeMateAtVertex? hne germ with
  | none =>
      left
      exact (seed.pairFoldCellLinkAt_degree_eq_one_iff_edgeMate_none
        hne germ).2 hmate
  | some other =>
      right
      have hle :
          @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
            (seed.pairFoldFaceCornerAtVertexFintype hne v)
            (seed.pairFoldFaceGermOutDart hne germ)
            (seed.pairFoldCellLinkEndpointFiberFintype hne
              (seed.pairFoldFaceGermOutDart hne germ)) ≤ 2 := by
        simpa [FiniteIncidenceMultigraph.degree,
          FiniteIncidenceMultigraph.endpointVertex,
          MinimalAreaRelatorBoundarySeed.pairFoldCellLinkEndpointDart,
          MinimalAreaRelatorBoundarySeed.pairFoldCellLinkAt] using
          seed.pairFoldCellLinkAt_degree_le_two hne
            (seed.pairFoldFaceGermOutDart hne germ)
      have hneOne :
          @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
            (seed.pairFoldFaceCornerAtVertexFintype hne v)
            (seed.pairFoldFaceGermOutDart hne germ)
            (seed.pairFoldCellLinkEndpointFiberFintype hne
              (seed.pairFoldFaceGermOutDart hne germ)) ≠ 1 := by
        intro hdegree
        have hnone :=
          (seed.pairFoldCellLinkAt_degree_eq_one_iff_edgeMate_none hne germ).1 hdegree
        rw [hmate] at hnone
        cases hnone
      have hpos :
          0 < @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
            (seed.pairFoldFaceCornerAtVertexFintype hne v)
            (seed.pairFoldFaceGermOutDart hne germ)
            (seed.pairFoldCellLinkEndpointFiberFintype hne
              (seed.pairFoldFaceGermOutDart hne germ)) := by
        have hpos' :
            0 < @Fintype.card
              {endpoint : seed.PairFoldCellLinkEndpoint hne v //
                seed.pairFoldCellLinkEndpointDart hne endpoint =
                  seed.pairFoldFaceGermOutDart hne germ}
              (seed.pairFoldCellLinkEndpointFiberFintype hne
                (seed.pairFoldFaceGermOutDart hne germ)) := by
          apply Fintype.card_pos_iff.mpr
          exact ⟨(seed.pairFoldCellLinkEndpointFiberEquiv hne
            (seed.pairFoldFaceGermOutDart hne germ)).symm ⟨germ, rfl⟩⟩
        simpa [FiniteIncidenceMultigraph.degree,
          FiniteIncidenceMultigraph.endpointVertex,
          MinimalAreaRelatorBoundarySeed.pairFoldCellLinkEndpointDart,
          MinimalAreaRelatorBoundarySeed.pairFoldCellLinkAt] using hpos'
      omega

/-- The second corner incidence is present exactly when a distinct face germ
is paired across the represented edge. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldCellLinkAt_degree_eq_two_iff_edgeMate_some
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (germ : seed.PairFoldFaceGermsAtVertex hne v) :
    @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
      (seed.pairFoldFaceCornerAtVertexFintype hne v)
      (seed.pairFoldFaceGermOutDart hne germ)
      (seed.pairFoldCellLinkEndpointFiberFintype hne
        (seed.pairFoldFaceGermOutDart hne germ)) = 2 ↔
      ∃ other, seed.pairFoldFaceEdgeMateAtVertex? hne germ = some other := by
  constructor
  · intro hdegree
    cases hmate : seed.pairFoldFaceEdgeMateAtVertex? hne germ with
    | none =>
        have hone := (seed.pairFoldCellLinkAt_degree_eq_one_iff_edgeMate_none
          hne germ).2 hmate
        omega
    | some other => exact ⟨other, rfl⟩
  · rintro ⟨other, hmate⟩
    rcases seed.pairFoldCellLinkAt_degree_eq_one_or_two hne germ with hone | htwo
    · have hnone := (seed.pairFoldCellLinkAt_degree_eq_one_iff_edgeMate_none
        hne germ).1 hone
      rw [hmate] at hnone
      cases hnone
    · exact htwo

/-- Every edge end in the supported actual corner-link component has exactly
one or two corner incidences; the component's simple-graph support contains
no stem-only isolated edge ends. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldCellLinkActualComponent_degree_eq_one_or_two
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (C : (twoPairingGraph (seed.pairFoldCornerPairingAtVertex hne (v := v))
      (seed.pairFoldEdgePairingAtVertex hne (v := v))).ConnectedComponent)
    (base : C.supp) {d : seed.PairFoldVertexLinkDart hne v}
    (hd : d ∈ ((seed.pairFoldCellLinkCornerAdjacencyAtVertex hne v).connectedComponentMk
      (seed.pairFoldFaceGermOutDart hne base.1)).supp) :
    @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
      (seed.pairFoldFaceCornerAtVertexFintype hne v) d
      (seed.pairFoldCellLinkEndpointFiberFintype hne d) = 1 ∨
    @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
      (seed.pairFoldFaceCornerAtVertexFintype hne v) d
      (seed.pairFoldCellLinkEndpointFiberFintype hne d) = 2 := by
  have hsupport := seed.pairFoldCellLinkComponent_output_image_eq_component_support
    hne C base
  have himage : ∃ germ : C.supp,
      seed.pairFoldFaceGermOutDart hne germ.1 = d := by
    have hd' : d ∈ {d | ∃ germ : C.supp,
        seed.pairFoldFaceGermOutDart hne germ.1 = d} := by
      rw [hsupport]
      exact hd
    exact hd'
  rcases himage with ⟨germ, houtput⟩
  have hdegree := seed.pairFoldCellLinkAt_degree_eq_one_or_two hne germ.1
  rw [houtput] at hdegree
  exact hdegree

/-- In each connected component of the face-germ link, the across-edge
pairing has either zero or two unmatched germs. The corner pairing is total,
so these are exactly the closed-cycle and exposed-path cases. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldFaceLinkComponent_boundary_count_zero_or_two
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (C : (twoPairingGraph (seed.pairFoldCornerPairingAtVertex hne (v := v))
      (seed.pairFoldEdgePairingAtVertex hne (v := v))).ConnectedComponent) :
    Nat.card {germ : C.supp //
        (componentRightPairing (seed.pairFoldCornerPairingAtVertex hne (v := v))
          (seed.pairFoldEdgePairingAtVertex hne (v := v)) C).partner germ = none} = 0 ∨
      Nat.card {germ : C.supp //
        (componentRightPairing (seed.pairFoldCornerPairingAtVertex hne (v := v))
          (seed.pairFoldEdgePairingAtVertex hne (v := v)) C).partner germ = none} = 2 := by
  classical
  let cornerPairing := seed.pairFoldCornerPairingAtVertex hne (v := v)
  let edgePairing := seed.pairFoldEdgePairingAtVertex hne (v := v)
  let cornerOnComponent := componentLeftPairing cornerPairing edgePairing C
  let edgeOnComponent := componentRightPairing cornerPairing edgePairing C
  letI : Fintype C.supp := Fintype.ofFinite _
  letI : DecidableEq C.supp := Classical.decEq _
  have hconn :
      (twoPairingGraph cornerOnComponent edgeOnComponent).Connected := by
    rw [twoPairingGraph_component_eq_induce cornerPairing edgePairing C]
    exact C.connected_toSimpleGraph
  have hslots := card_unpaired_pairing_slots_eq_zero_or_two_of_connected
    cornerOnComponent edgeOnComponent hconn
  let cornerUnmatched := {germ : C.supp // cornerOnComponent.partner germ = none}
  let edgeUnmatched := {germ : C.supp // edgeOnComponent.partner germ = none}
  have hcornerEmpty : IsEmpty cornerUnmatched := by
    refine ⟨?_⟩
    rintro ⟨germ, hnone⟩
    have hglobal :=
      (componentLeftPairing_partner_none_iff cornerPairing edgePairing C germ).mp
        hnone
    simp [cornerPairing, MinimalAreaRelatorBoundarySeed.pairFoldCornerPairingAtVertex]
      at hglobal
  letI : IsEmpty cornerUnmatched := hcornerEmpty
  have hcard : Nat.card (cornerUnmatched ⊕ edgeUnmatched) =
      Nat.card edgeUnmatched := by
    simp [cornerUnmatched, edgeUnmatched]
  rcases hslots with hzero | htwo
  · left
    calc
      Nat.card edgeUnmatched = Nat.card (cornerUnmatched ⊕ edgeUnmatched) :=
        hcard.symm
      _ = 0 := hzero
  · right
    calc
      Nat.card edgeUnmatched = Nat.card (cornerUnmatched ⊕ edgeUnmatched) :=
        hcard.symm
      _ = 2 := htwo

/-- In the face-germ transition graph, each connected component has either no
degree-one germs or exactly two exposed germs. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldFaceLinkComponent_degree_one_count_zero_or_two
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (C : (twoPairingGraph (seed.pairFoldCornerPairingAtVertex hne (v := v))
      (seed.pairFoldEdgePairingAtVertex hne (v := v))).ConnectedComponent) :
    Nat.card {germ : C.supp //
        ((seed.pairFoldFaceLinkGraph hne v).neighborFinset germ.1).card = 1} = 0 ∨
      Nat.card {germ : C.supp //
        ((seed.pairFoldFaceLinkGraph hne v).neighborFinset germ.1).card = 1} = 2 := by
  classical
  let cornerPairing := seed.pairFoldCornerPairingAtVertex hne (v := v)
  let edgePairing := seed.pairFoldEdgePairingAtVertex hne (v := v)
  let degreeOne := {germ : C.supp //
    ((seed.pairFoldFaceLinkGraph hne v).neighborFinset germ.1).card = 1}
  let exposed := {germ : C.supp //
    (componentRightPairing cornerPairing edgePairing C).partner germ = none}
  have hpred (germ : C.supp) :
      ((seed.pairFoldFaceLinkGraph hne v).neighborFinset germ.1).card = 1 ↔
        (componentRightPairing cornerPairing edgePairing C).partner germ = none := by
    calc
      _ ↔ seed.pairFoldFaceEdgeMateAtVertex? hne germ.1 = none :=
        seed.pairFoldFaceLinkGraph_degree_eq_one_iff_edgeMate_none hne germ.1
      _ ↔ (componentRightPairing cornerPairing edgePairing C).partner germ = none :=
        (componentRightPairing_partner_none_iff cornerPairing edgePairing C germ).symm
  let degreeOneEquivExposed : degreeOne ≃ exposed := {
    toFun := fun germ => ⟨germ.1, (hpred germ.1).mp germ.2⟩
    invFun := fun germ => ⟨germ.1, (hpred germ.1).mpr germ.2⟩
    left_inv := by
      intro germ
      apply Subtype.ext
      rfl
    right_inv := by
      intro germ
      apply Subtype.ext
      rfl }
  have hboundary := seed.pairFoldFaceLinkComponent_boundary_count_zero_or_two
    hne C
  rcases hboundary with hzero | htwo
  · left
    calc
      Nat.card degreeOne = Nat.card exposed := Nat.card_congr degreeOneEquivExposed
      _ = 0 := hzero
  · right
    calc
      Nat.card degreeOne = Nat.card exposed := Nat.card_congr degreeOneEquivExposed
      _ = 2 := htwo

/-- The face-germ endpoint count transfers to the actual corner-incidence
multigraph: within one transition component, its degree-one oriented edge ends
are in bijection with the degree-one face germs. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldCellLinkComponent_degree_one_dart_count_zero_or_two
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (C : (twoPairingGraph (seed.pairFoldCornerPairingAtVertex hne (v := v))
      (seed.pairFoldEdgePairingAtVertex hne (v := v))).ConnectedComponent) :
    Nat.card {d : seed.PairFoldVertexLinkDart hne v //
      (∃ germ : C.supp,
        seed.pairFoldFaceGermOutDart hne germ.1 = d) ∧
      @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
        (seed.pairFoldFaceCornerAtVertexFintype hne v) d
        (seed.pairFoldCellLinkEndpointFiberFintype hne d) = 1} = 0 ∨
    Nat.card {d : seed.PairFoldVertexLinkDart hne v //
      (∃ germ : C.supp,
        seed.pairFoldFaceGermOutDart hne germ.1 = d) ∧
      @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
        (seed.pairFoldFaceCornerAtVertexFintype hne v) d
        (seed.pairFoldCellLinkEndpointFiberFintype hne d) = 1} = 2 := by
  classical
  letI : Fintype C.supp := Fintype.ofFinite _
  letI : DecidableEq C.supp := Classical.decEq _
  letI : Fintype (seed.pairFoldCellLinkAt hne v).Edge :=
    seed.pairFoldFaceCornerAtVertexFintype hne v
  let germDegreeOne := {germ : C.supp //
    ((seed.pairFoldFaceLinkGraph hne v).neighborFinset germ.1).card = 1}
  let linkDegreeOne := {d : seed.PairFoldVertexLinkDart hne v //
    (∃ germ : C.supp, seed.pairFoldFaceGermOutDart hne germ.1 = d) ∧
      @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
        (seed.pairFoldFaceCornerAtVertexFintype hne v) d
        (seed.pairFoldCellLinkEndpointFiberFintype hne d) = 1}
  let toLinkDegreeOne : germDegreeOne → linkDegreeOne := fun germ =>
    ⟨seed.pairFoldFaceGermOutDart hne germ.1.1,
      ⟨⟨germ.1, rfl⟩,
        (seed.pairFoldCellLinkAt_degree_eq_one_iff_edgeMate_none
          hne germ.1.1).2
          ((seed.pairFoldFaceLinkGraph_degree_eq_one_iff_edgeMate_none
            hne germ.1.1).1 germ.2)⟩⟩
  have hmate_none (germ : germDegreeOne) :
      seed.pairFoldFaceEdgeMateAtVertex? hne germ.1.1 = none :=
    (seed.pairFoldFaceLinkGraph_degree_eq_one_iff_edgeMate_none
      hne germ.1.1).1 germ.2
  have hinjective : Function.Injective toLinkDegreeOne := by
    intro germA germB heq
    apply Subtype.ext
    apply Subtype.ext
    have houtputs : seed.pairFoldFaceGermOutDart hne germA.1.1 =
        seed.pairFoldFaceGermOutDart hne germB.1.1 := by
      exact congrArg Subtype.val heq
    rcases (seed.pairFoldFaceGermOutDart_eq_iff hne
      germA.1.1 germB.1.1).mp houtputs with heqGerm | hedge
    · exact heqGerm
    · have hmate := seed.pairFoldFaceEdgeMateAtVertex?_of_edgeStep
        hne germA.1.1 germB.1.1 hedge
      rw [hmate_none germA] at hmate
      cases hmate
  have hsurjective : Function.Surjective toLinkDegreeOne := by
    intro d
    rcases d.2 with ⟨⟨germ, hout⟩, hdegree⟩
    have hdegreeOut :
        @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
          (seed.pairFoldFaceCornerAtVertexFintype hne v)
          (seed.pairFoldFaceGermOutDart hne germ.1)
          (seed.pairFoldCellLinkEndpointFiberFintype hne
            (seed.pairFoldFaceGermOutDart hne germ.1)) = 1 := by
      rw [hout]
      exact hdegree
    have hmate := (seed.pairFoldCellLinkAt_degree_eq_one_iff_edgeMate_none
      hne germ.1).1 hdegreeOut
    have hfaceDegree :=
      (seed.pairFoldFaceLinkGraph_degree_eq_one_iff_edgeMate_none
        hne germ.1).2 hmate
    refine ⟨⟨germ, hfaceDegree⟩, ?_⟩
    apply Subtype.ext
    exact hout
  let linkEquiv : germDegreeOne ≃ linkDegreeOne :=
    Equiv.ofBijective toLinkDegreeOne ⟨hinjective, hsurjective⟩
  have hfaceCount := seed.pairFoldFaceLinkComponent_degree_one_count_zero_or_two
    hne C
  rcases hfaceCount with hzero | htwo
  · left
    calc
      Nat.card linkDegreeOne = Nat.card germDegreeOne :=
        Nat.card_congr linkEquiv.symm
      _ = 0 := hzero
  · right
    calc
      Nat.card linkDegreeOne = Nat.card germDegreeOne :=
        Nat.card_congr linkEquiv.symm
      _ = 2 := htwo

/-- Every connected component of the actual corner-adjacency graph that
contains a face end has zero or two degree-one vertices in the incidence
multigraph. This is the endpoint profile of a cycle or a path, with parallel
corner occurrences retained in the degree count. -/
theorem MinimalAreaRelatorBoundarySeed.pairFoldCellLinkActualComponent_degree_one_count_zero_or_two
    {α : Type*} [Fintype α] [DecidableEq α]
    {P : SymmetrizedPresentation α} {w : FreeGroup α}
    (seed : MinimalAreaRelatorBoundarySeed P.relators w) (hne : w ≠ 1)
    {v : seed.pairFoldFiniteGraph.toDartGraph.Vertex}
    (C : (twoPairingGraph (seed.pairFoldCornerPairingAtVertex hne (v := v))
      (seed.pairFoldEdgePairingAtVertex hne (v := v))).ConnectedComponent)
    (base : C.supp) :
    Nat.card {d : seed.PairFoldVertexLinkDart hne v //
      d ∈ ((seed.pairFoldCellLinkCornerAdjacencyAtVertex hne v).connectedComponentMk
        (seed.pairFoldFaceGermOutDart hne base.1)).supp ∧
      @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
        (seed.pairFoldFaceCornerAtVertexFintype hne v) d
        (seed.pairFoldCellLinkEndpointFiberFintype hne d) = 1} = 0 ∨
    Nat.card {d : seed.PairFoldVertexLinkDart hne v //
      d ∈ ((seed.pairFoldCellLinkCornerAdjacencyAtVertex hne v).connectedComponentMk
        (seed.pairFoldFaceGermOutDart hne base.1)).supp ∧
      @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
        (seed.pairFoldFaceCornerAtVertexFintype hne v) d
        (seed.pairFoldCellLinkEndpointFiberFintype hne d) = 1} = 2 := by
  classical
  let G := seed.pairFoldCellLinkCornerAdjacencyAtVertex hne v
  let D := G.connectedComponentMk (seed.pairFoldFaceGermOutDart hne base.1)
  let actualDegreeOne := {d : seed.PairFoldVertexLinkDart hne v //
    d ∈ D.supp ∧
      @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
        (seed.pairFoldFaceCornerAtVertexFintype hne v) d
        (seed.pairFoldCellLinkEndpointFiberFintype hne d) = 1}
  let representedDegreeOne := {d : seed.PairFoldVertexLinkDart hne v //
    (∃ germ : C.supp, seed.pairFoldFaceGermOutDart hne germ.1 = d) ∧
      @FiniteIncidenceMultigraph.degree (seed.pairFoldCellLinkAt hne v)
        (seed.pairFoldFaceCornerAtVertexFintype hne v) d
        (seed.pairFoldCellLinkEndpointFiberFintype hne d) = 1}
  have hsupport := seed.pairFoldCellLinkComponent_output_image_eq_component_support
    hne C base
  have hmem (d : seed.PairFoldVertexLinkDart hne v) :
      d ∈ D.supp ↔ ∃ germ : C.supp,
        seed.pairFoldFaceGermOutDart hne germ.1 = d := by
    constructor
    · intro hd
      have hi : d ∈ {d | ∃ germ : C.supp,
          seed.pairFoldFaceGermOutDart hne germ.1 = d} := by
        rw [hsupport]
        exact hd
      exact hi
    · intro hd
      have hi : d ∈ {d | ∃ germ : C.supp,
          seed.pairFoldFaceGermOutDart hne germ.1 = d} := hd
      rw [hsupport] at hi
      exact hi
  let componentEquiv : actualDegreeOne ≃ representedDegreeOne := {
    toFun := fun d => ⟨d.1, ⟨(hmem d.1).mp d.2.1, d.2.2⟩⟩
    invFun := fun d => ⟨d.1, ⟨(hmem d.1).mpr d.2.1, d.2.2⟩⟩
    left_inv := by
      intro d
      apply Subtype.ext
      rfl
    right_inv := by
      intro d
      apply Subtype.ext
      rfl }
  have hrepresented :=
    seed.pairFoldCellLinkComponent_degree_one_dart_count_zero_or_two hne C
  rcases hrepresented with hzero | htwo
  · left
    calc
      Nat.card actualDegreeOne = Nat.card representedDegreeOne :=
        Nat.card_congr componentEquiv
      _ = 0 := by simpa [representedDegreeOne] using hzero
  · right
    calc
      Nat.card actualDegreeOne = Nat.card representedDegreeOne :=
        Nat.card_congr componentEquiv
      _ = 2 := by simpa [representedDegreeOne] using htwo

end GreendlingerDehn
